(function(root){
'use strict';
const F=[
{id:'coach-analytics-tools',name:'Coach Analytics Tools',icon:'icons/analyticsfolder.png',members:['coaching-gaps','kpi-impact','qa-scores'],description:'Coaching Gaps, KPI Impact, and QA Scores'},
{id:'general-apps',name:'General Apps',icon:'icons/otherfolder.png',members:['coach-timeline','audit-checklist'],description:'Coach Timeline and Audit / Checklist'},
{id:'under-construction',name:'Under Construction',icon:'icons/underconstructionfolder.png',members:['people-profiles','coaching-command-center'],description:'People Profiles and Coaching Command Center'}
];
const enabled=new Set((((root.COACHTOOLS_MANIFEST||{}).apps)||[]).filter(a=>a&&a.enabled!==false).map(a=>a.id));
const dialogs=new Map(); let grid,observer,busy=false,rendered=false;
function el(tag,cls,text){const n=document.createElement(tag);if(cls)n.className=cls;if(text!=null)n.textContent=text;return n;}
function icon(folder){const w=el('span','app-icon'),fb=el('span','fallback-initials',folder.name.split(/\s+/).map(x=>x[0]).join('').slice(0,3).toUpperCase()),im=el('img');im.alt='';im.src=folder.icon;im.loading='eager';im.addEventListener('load',()=>w.classList.add('loaded'));im.addEventListener('error',()=>im.remove());w.append(fb,im);return w;}
function selectVisual(tile){document.querySelectorAll('[data-app-id]').forEach(n=>{const on=n===tile;n.classList.toggle('selected',on);n.setAttribute('aria-selected',String(on));});document.querySelectorAll('.desktop-folder-card').forEach(n=>{n.classList.remove('selected');n.setAttribute('aria-selected','false');});}
function ensureDialog(folder){if(dialogs.has(folder.id))return dialogs.get(folder.id);const d=el('dialog','folder-dialog');d.dataset.folderId=folder.id;const shell=el('section','folder-dialog-shell'),head=el('header','folder-dialog-header'),im=el('img','folder-dialog-icon'),copy=el('div','folder-dialog-heading'),ey=el('p','eyebrow','CoachTools folder'),title=el('h2','',folder.name),desc=el('p','',folder.description),close=el('button','folder-dialog-close','×'),g=el('div','folder-app-grid');im.alt='';im.src=folder.icon;im.addEventListener('error',()=>{im.hidden=true;});close.type='button';close.setAttribute('aria-label','Close '+folder.name);g.dataset.folderGrid=folder.id;g.setAttribute('role','listbox');g.setAttribute('aria-label',folder.name+' applications');copy.append(ey,title,desc);head.append(im,copy,close);shell.append(head,g);d.append(shell);close.addEventListener('click',()=>d.close());d.addEventListener('click',e=>{if(e.target===d)d.close();});g.addEventListener('click',e=>{const t=e.target.closest('[data-app-id]');if(t)selectVisual(t);});g.addEventListener('contextmenu',e=>{const t=e.target.closest('[data-app-id]');if(t)selectVisual(t);});g.addEventListener('dblclick',e=>{if(e.target.closest('[data-app-id]'))root.setTimeout(()=>d.close(),0);});document.body.append(d);const out={dialog:d,grid:g};dialogs.set(folder.id,out);return out;}
function open(folder){const d=ensureDialog(folder).dialog;if(typeof d.showModal==='function'){if(!d.open)d.showModal();}else d.setAttribute('open','');}
function card(folder,count){const b=el('button','app-card desktop-folder-card');b.type='button';b.dataset.folderId=folder.id;b.setAttribute('role','option');b.setAttribute('aria-selected','false');b.setAttribute('aria-label','('+count+') '+folder.name+'. Double-click to open.');const main=el('span','app-card-main'),name=el('span','app-name','('+count+') '+folder.name);main.append(icon(folder),name);b.append(main);b.addEventListener('click',()=>{document.querySelectorAll('[data-app-id]').forEach(n=>{n.classList.remove('selected');n.setAttribute('aria-selected','false');});document.querySelectorAll('.desktop-folder-card').forEach(n=>{const on=n===b;n.classList.toggle('selected',on);n.setAttribute('aria-selected',String(on));});});b.addEventListener('dblclick',()=>open(folder));b.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();open(folder);}});return b;}
function organize(){if(!grid||busy)return;busy=true;if(observer)observer.disconnect();try{grid.querySelectorAll('.desktop-folder-card').forEach(n=>n.remove());const tiles=[...grid.querySelectorAll('[data-app-id]')];if(tiles.length)rendered=true;const frag=document.createDocumentFragment();F.forEach(folder=>{const moved=tiles.filter(t=>folder.members.includes(t.dataset.appId)),box=ensureDialog(folder);if(rendered)box.grid.replaceChildren(...moved);const count=rendered?moved.length:folder.members.filter(id=>enabled.has(id)).length;if(count)frag.append(card(folder,count));else if(box.dialog.open)box.dialog.close();});grid.prepend(frag);}finally{if(observer)observer.observe(grid,{childList:true});busy=false;}}
function start(){grid=document.getElementById('appGrid');if(!grid)return;F.forEach(ensureDialog);organize();observer=new MutationObserver(organize);observer.observe(grid,{childList:true});}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})(window);
