/* DOM event wiring, optional test loader, lifecycle persistence, and startup.
 * Behavior-preserving extraction from the definitive All-Star application.
 */
'use strict';

function wire(){
  const previewSearch=el('columnPreviewSearch'); if(previewSearch) previewSearch.oninput=renderColumnPreviewValues;
  ['columnPreviewCloseBtn','columnPreviewDoneBtn'].forEach(pid=>{ const b=el(pid); if(b) b.onclick=closeColumnPreview; });
  document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>closeModal(b.dataset.close));
  if(els.openTroubleshootBtn) els.openTroubleshootBtn.onclick=()=>openTroubleshoot('qa');
  if(els.fixTeamsBtn) els.fixTeamsBtn.onclick=renderFixTeamsReview;
  if(els.applyFixTeamsBtn) els.applyFixTeamsBtn.onclick=applySelectedFixTeams;
  if(els.applyFixRepMatchesBtn) els.applyFixRepMatchesBtn.onclick=applySelectedFixRepMatches;
  if(els.cancelFixTeamsBtn) els.cancelFixTeamsBtn.onclick=()=>els.fixTeamsPanel?.classList.add('hidden');
  if(els.categorizeDataBtn) els.categorizeDataBtn.onclick=categorizeImportedData;
  if(els.viewSpreadsheetDataBtn) els.viewSpreadsheetDataBtn.onclick=renderSpreadsheetDataPreview;
  if(els.packageDataBtn) els.packageDataBtn.onclick=packageImportedData;
  if(els.saveImportCacheBtn) els.saveImportCacheBtn.onclick=()=>saveImportedDataToIndexedDB('manual cache save',{silent:false,full:true});
  if(els.loadImportCacheBtn) els.loadImportCacheBtn.onclick=()=>loadImportedDataFromIndexedDB({showProgress:true,alert:true});
  if(els.persistImportCacheBtn) els.persistImportCacheBtn.onclick=requestImportCachePersistence;
  if(els.clearImportCacheBtn) els.clearImportCacheBtn.onclick=clearImportedDataIndexedDB;
  if(els.addCustomSourceBtn) els.addCustomSourceBtn.onclick=()=>{ state.pendingCustomName=(prompt('Name this custom source','Weekly Stats')||'').trim(); if(state.pendingCustomName) els.customSourceFile.click(); };
  if(els.customSourceFile) els.customSourceFile.onchange=e=>{const f=e.target.files[0]; if(f) loadCustomSourceFile(f,state.pendingCustomName||'Custom Source'); e.target.value=''; state.pendingCustomName='';};
  if(els.troubleSourceSelect) els.troubleSourceSelect.onchange=()=>{ state.troubleshoot.source=els.troubleSourceSelect.value; const cfg=getSourceSetting(activeModelForImport(),state.troubleshoot.source); const book=bookForSource(state.troubleshoot.source); state.troubleshoot.sheetName=preferredRequiredSheetForSource(book.sheetNames||[],state.troubleshoot.source)||cfg.sheetName||book.selectedSheets[state.troubleshoot.source]||book.sheetNames?.[0]||''; state.troubleshoot.headerRow=Math.max(1,Number(cfg.headerRow)||1); state.troubleshoot.startCol=Math.max(1,Number(cfg.startCol)||1); state.troubleshoot.manualHeaders=JSON.parse(JSON.stringify(cfg.manualHeaders||[])); renderTroubleshootControls(); renderTroubleshootPreview(); };
  if(els.troubleSheetSelect) els.troubleSheetSelect.onchange=()=>{ const suggested=packageSheetToSource(els.troubleSheetSelect.value); if(suggested && sourceHasImportedData(suggested) && suggested!==state.troubleshoot.source){ state.troubleshoot.source=suggested; state.troubleshoot.sheetName=els.troubleSheetSelect.value; const cfg=getSourceSetting(activeModelForImport(),suggested); state.troubleshoot.headerRow=Math.max(1,Number(cfg.headerRow)||1); state.troubleshoot.startCol=Math.max(1,Number(cfg.startCol)||1); state.troubleshoot.manualHeaders=JSON.parse(JSON.stringify(cfg.manualHeaders||[])); renderTroubleshootControls(); } else state.troubleshoot.sheetName=els.troubleSheetSelect.value; ensureTroubleshootSheetLoaded().finally(()=>renderTroubleshootPreview()); };
  if(els.troubleHeaderRowInput) els.troubleHeaderRowInput.onchange=()=>{ state.troubleshoot.headerRow=Math.max(1,Number(els.troubleHeaderRowInput.value)||1); renderTroubleshootPreview(false); };
  if(els.troubleStartColInput) els.troubleStartColInput.onchange=()=>{ state.troubleshoot.startCol=Math.max(1,Number(els.troubleStartColInput.value)||1); renderTroubleshootPreview(false); };
  if(els.troublePreviewBtn) els.troublePreviewBtn.onclick=()=>renderTroubleshootPreview();
  if(els.troubleApplyBtn) els.troubleApplyBtn.onclick=applyTroubleshootSelection;
  if(els.troubleApplyFootBtn) els.troubleApplyFootBtn.onclick=applyTroubleshootSelection;
  if(els.troubleDeclareHeaderBtn) els.troubleDeclareHeaderBtn.onclick=declareTroubleHeader;
  ['troubleNameMode','troubleFullNameColumn','troubleFirstNameColumn','troubleLastNameColumn','troubleConvertLastFirst','troubleTeamColumn','troubleSkipTeamBuild','troubleDateColumn'].forEach(id=>{ if(els[id]) els[id].onchange=renderTroubleshootHeaderPreview; });
  if(els.troubleUseDateColumn) els.troubleUseDateColumn.onchange=()=>{ if(els.troubleDateColumn) els.troubleDateColumn.disabled=!els.troubleUseDateColumn.checked; };
  els.categoriesDrop.onchange=()=>{ if(els.categoriesDrop.value==='models'){ renderModelList(); openModal('modelsModal'); } if(els.categoriesDrop.value==='massHeaders') openMassHeaderCheck(); if(els.categoriesDrop.value==='metrics') openMetricsPage(); els.categoriesDrop.value=''; };
  els.importDrop.onchange=()=>{ if(els.importDrop.value==='data'){ renderTeamTotalsImportControls(); openModal('importModal'); } if(els.importDrop.value==='roster') openRosterReassignment(); if(els.importDrop.value==='teams') openTeamsImported(); if(els.importDrop.value==='orgs') openOrgBuilder(); els.importDrop.value=''; };
  if(els.qualtricsEmailBtn) els.qualtricsEmailBtn.onclick=openQualtricsEmailWorkspace;
  if(els.refreshQualtricsDataBtn) els.refreshQualtricsDataBtn.onclick=()=>sendQualtricsCoreFiles(true);
  if(els.clearQualtricsDataBtn) els.clearQualtricsDataBtn.onclick=clearQualtricsEmailData;
  if(els.loadQualtricsWeeklyBtn) els.loadQualtricsWeeklyBtn.onclick=sendQualtricsWeeklyStats;
  if(els.qualtricsStatsSource) els.qualtricsStatsSource.onchange=()=>{ state.savedQualtricsStatsSource=els.qualtricsStatsSource.value; saveRunSettings(); if(els.qualtricsBridgeStatus) els.qualtricsBridgeStatus.textContent='Weekly Stats selection changed. Nothing has loaded or calculated; press Load Selected Weekly Stats when ready.'; };
  window.addEventListener('message',handleQualtricsMessage);
  if(els.teamManagerList) els.teamManagerList.onclick=e=>{ const b=e.target.closest('[data-team-pick]'); if(b) loadTeamDetails(b.dataset.teamPick); };
  if(els.teamManagerSearch) els.teamManagerSearch.oninput=debounce(()=>renderTeamsImportedModal(),180);
  if(els.teamRepSearch) els.teamRepSearch.oninput=debounce(()=>{ if(state.activeTeam) renderCachedTeamDetails(state.activeTeam); },180);
  const clearAliases=(area='')=>{ if(area){ [...state.repAliases.keys()].forEach(k=>{ const v=state.repAliases.get(k); if(v?.sourceArea===area || v?.sourceArea==='global') state.repAliases.delete(k); }); state.quarantinedRepAliases=(state.quarantinedRepAliases||[]).filter(v=>v?.sourceArea!==area && v?.sourceArea!=='global'); } else { state.repAliases.clear(); state.quarantinedRepAliases=[]; } saveRepAliases(); applyRepAliasMappingsToAllRows(); markDataIndexDirty('representative aliases cleared'); renderTeamsImportedModal(); };
  if(els.rebuildControlRosterBtn) els.rebuildControlRosterBtn.onclick=async()=>{ revalidateRepAliases(); applyRepAliasMappingsToAllRows(); renderTeamsImportedModal(); alert('Roster rebuild safety checks completed. Re-upload Control workbooks if this cache was loaded under an older roster schema.'); };
  if(els.clearAllRepAliasesBtn) els.clearAllRepAliasesBtn.onclick=()=>clearAliases('');
  if(els.clearRetailRepAliasesBtn) els.clearRetailRepAliasesBtn.onclick=()=>clearAliases('retail');
  if(els.clearReferralRepAliasesBtn) els.clearReferralRepAliasesBtn.onclick=()=>clearAliases('referral');
  if(els.refreshMassHeaderBtn) els.refreshMassHeaderBtn.onclick=renderMassHeaderCheck;
  if(els.applyMassHeaderBtn) els.applyMassHeaderBtn.onclick=applyAllMassHeaderFixes;
  if(els.massShowAllHeaders) els.massShowAllHeaders.onchange=renderMassHeaderCheck;
  els.runBtn.onclick=async()=>{
    const t0=performance.now();
    state.teamSearch='';
    if(els.teamSearchInput) els.teamSearchInput.value='';
    try{
      console.groupCollapsed('[All Star Run] Open Run modal');
      console.time('[All Star Run] Model-selector rendering'); populateRunModels(); console.timeEnd('[All Star Run] Model-selector rendering');
      loadRunSettings();
      updateRunQADateField();
      console.time('[All Star Run] Team rendering'); renderTeamSelect(); console.timeEnd('[All Star Run] Team rendering');
      console.time('[All Star Run] Organization rendering'); renderRunOrgSelect(); console.timeEnd('[All Star Run] Organization rendering');
      setDefaultRunDates();
      renderMultiRunOrgSelect(); applyRunMode(state.runMode);
      openModal('runModal');
      console.info('[All Star Run] Global rebuild avoided', !dataIndexReady());
      console.info('[All Star Run] Time until Run modal visible', Math.round(performance.now()-t0)+'ms');
      console.groupEnd();
      await new Promise(resolve=>requestAnimationFrame(()=>resolve()));
      setTimeout(beginSelectedModelPreparation,0);
    }catch(err){ console.error(err); alert('Run setup failed. Check the console for details.'); }
    finally{ hideProgress(); }
  };
  if(els.pdfDrop) els.pdfDrop.onchange=()=>{ const v=els.pdfDrop.value; els.pdfDrop.value=''; if(v==='export') exportPDF(); if(v==='options') openPdfOptionsModal(); };
  [els.pdfTitleInput,els.pdfSubtitleInput,els.pdfColorScheme,els.pdfCustomPrimary,els.pdfCustomSecondary,els.pdfCustomHeaderText,els.pdfCustomLightFill,els.pdfOrientation,els.pdfPageSize,els.pdfWinCoach,els.pdfWinRepTeam,els.pdfWinRepOverall,els.pdfTop50,els.pdfEachTeam,els.pdfCoaches,els.pdfAllReps].forEach(x=>{ if(x) x.oninput=x.onchange=()=>{ if(x===els.pdfColorScheme) els.pdfCustomColors?.classList.toggle('hidden',x.value!=='custom'); updatePdfOptionsSummary(); }; });
  if(els.pdfWinnerSummaryBtn) els.pdfWinnerSummaryBtn.onclick=()=>{ els.pdfWinCoach.checked=true; els.pdfWinRepTeam.checked=true; els.pdfWinRepOverall.checked=true; els.pdfTop50.checked=false; els.pdfEachTeam.checked=false; els.pdfCoaches.checked=false; els.pdfAllReps.checked=false; updatePdfOptionsSummary(); };
  if(els.pdfFullReportBtn) els.pdfFullReportBtn.onclick=()=>{ els.pdfWinCoach.checked=true; els.pdfWinRepTeam.checked=true; els.pdfWinRepOverall.checked=true; els.pdfTop50.checked=true; els.pdfEachTeam.checked=true; els.pdfCoaches.checked=true; els.pdfAllReps.checked=true; updatePdfOptionsSummary(); };
  if(els.pdfClearBreakdownsBtn) els.pdfClearBreakdownsBtn.onclick=()=>{ els.pdfTop50.checked=false; els.pdfEachTeam.checked=false; els.pdfCoaches.checked=false; els.pdfAllReps.checked=false; updatePdfOptionsSummary(); };
  if(els.pdfRestoreDefaultsBtn) els.pdfRestoreDefaultsBtn.onclick=()=>{ state.pdfOptions=defaultPdfOptions(); populatePdfOptionsModal(); };
  if(els.pdfSaveOptionsBtn) els.pdfSaveOptionsBtn.onclick=()=>{ const o=readPdfOptionsFromModal(); if(!pdfHasAnyContent(o)) return alert('Select at least one winner or breakdown option.'); savePdfOptions(o); closeModal('pdfOptionsModal'); };
  if(els.pdfSaveExportBtn) els.pdfSaveExportBtn.onclick=()=>{ const o=readPdfOptionsFromModal(); if(!pdfHasAnyContent(o)) return alert('Select at least one winner or breakdown option.'); savePdfOptions(o); closeModal('pdfOptionsModal'); exportPDF(); };
  els.clearOutputBtn.onclick=()=>{els.workArea.innerHTML='<div class="empty"></div>';};
  if(els.researchBtn) els.researchBtn.onchange=async()=>{ const v=els.researchBtn.value; els.researchBtn.value=''; if(v==='listTester') openListTester(); if(v==='open') await openResearchWorkspace(); if(v==='clear') clearResearchItemsWithConfirm(); };
  if(els.listTesterBtn) els.listTesterBtn.onclick=openListTester;
  if(els.runListTesterBtn) els.runListTesterBtn.onclick=runListTester;
  if(els.clearListTesterBtn) els.clearListTesterBtn.onclick=clearListTester;
  if(els.copyListTesterCoachesBtn) els.copyListTesterCoachesBtn.onclick=copyListTesterCoaches;
  if(els.exportListTesterBtn) els.exportListTesterBtn.onclick=exportListTesterResults;
  if(els.exportListTesterPdfBtn) els.exportListTesterPdfBtn.onclick=exportListTesterPdf;
  if(els.listTesterInput) els.listTesterInput.addEventListener('keydown',e=>{ if((e.ctrlKey||e.metaKey)&&e.key==='Enter'){ e.preventDefault(); runListTester(); } });
  if(els.listTesterCheckEnabled) els.listTesterCheckEnabled.onchange=()=>{ updateListTesterCheckMeta(); };
  if(els.listTesterCheckPreset) els.listTesterCheckPreset.onchange=applyListTesterCheckPreset;
  if(els.listTesterCheckSource) els.listTesterCheckSource.onchange=()=>populateListTesterCheckHeaders({keepHeader:false,keepDate:false});
  if(els.listTesterCheckHeader) els.listTesterCheckHeader.onchange=updateListTesterCheckMeta;
  if(els.listTesterCheckDateHeader) els.listTesterCheckDateHeader.onchange=updateListTesterCheckMeta;
  if(els.listTesterCheckContains) els.listTesterCheckContains.oninput=debounce(updateListTesterCheckMeta,120);
  [els.listTesterCheckStartDate,els.listTesterCheckEndDate].forEach(x=>{ if(x) x.onchange=updateListTesterCheckMeta; });
  if(els.addResearchItemBtn) els.addResearchItemBtn.onclick=()=>openResearchItemEditor(null); if(els.researchApplyTemplateBtn) els.researchApplyTemplateBtn.onclick=applyResearchTemplate;
  [[els.researchAddIncludeOrgBtn,'includeOrgs',els.researchIncludeOrgInput],[els.researchAddIncludeTeamBtn,'includeTeams',els.researchIncludeTeamInput],[els.researchAddIncludeRepBtn,'includeReps',els.researchIncludeRepInput],[els.researchAddExcludeOrgBtn,'excludeOrgs',els.researchExcludeOrgInput],[els.researchAddExcludeTeamBtn,'excludeTeams',els.researchExcludeTeamInput],[els.researchAddExcludeRepBtn,'excludeReps',els.researchExcludeRepInput]].forEach(([button,type,input])=>{ if(button) button.onclick=()=>addResearchPopulationSelection(type,input); if(input) input.addEventListener('keydown',e=>{ if(e.key==='Enter'){ e.preventDefault(); addResearchPopulationSelection(type,input); } }); });
  if(els.researchTypedMeasure) els.researchTypedMeasure.onchange=renderResearchTypedMeasureMeta;
  if(els.researchMissingBehavior) els.researchMissingBehavior.onchange=renderResearchTypedMeasureMeta;
  if(els.researchUseTypedMeasureBtn) els.researchUseTypedMeasureBtn.onclick=()=>applyResearchTypedMeasureToEditor(false);
  if(els.researchAddTypedMeasureColumnBtn) els.researchAddTypedMeasureColumnBtn.onclick=()=>applyResearchTypedMeasureToEditor(true);
  if(els.researchPreviewMeasureSamplesBtn) els.researchPreviewMeasureSamplesBtn.onclick=previewResearchMeasureSamples;
  document.querySelectorAll('[data-guided-template]').forEach(b=>b.onclick=()=>applyGuidedResearchTemplate(b.dataset.guidedTemplate));
  if(els.addGuidedConditionBtn) els.addGuidedConditionBtn.onclick=()=>{ state.editingGuidedResearchActive=true; state.editingGuidedResearchConditions=state.editingGuidedResearchConditions||[]; state.editingGuidedResearchConditions.push({id:id(),logic:state.editingGuidedResearchConditions.length?'and':'and',source:els.guidedPrimarySource?.value||els.researchSource?.value||'',field:'',expression:false,operator:'contains',value:'',value2:'',caseSensitive:false,exactPhrase:false,normalizeSpacing:true}); renderGuidedResearchConditions(); activateGuidedResearch(); };
  if(els.guidedEvidenceSources) els.guidedEvidenceSources.onchange=()=>{ const selected=guidedSelectedEvidenceSources(); if(selected.length&&!selected.includes(els.guidedPrimarySource.value)) els.guidedPrimarySource.value=selected[0]; activateGuidedResearch(); };
  if(els.guidedPrimarySource) els.guidedPrimarySource.onchange=()=>{ const primary=els.guidedPrimarySource.value; if(els.guidedEvidenceSources&&![...els.guidedEvidenceSources.selectedOptions].some(o=>o.value===primary)){ const opt=[...els.guidedEvidenceSources.options].find(o=>o.value===primary); if(opt) opt.selected=true; } populateResearchFieldSelectors({source:primary}); renderGuidedResearchConditions(); activateGuidedResearch(); };
  if(els.guidedRecordType) els.guidedRecordType.onchange=()=>{ const source=els.guidedRecordType.value; if(source!=='custom'&&guidedSourceChoices().some(o=>o.value===source)){ els.guidedPrimarySource.value=source; [...els.guidedEvidenceSources.options].forEach(o=>{ if(o.value===source) o.selected=true; }); } activateGuidedResearch(); };
  ['guidedResearchSubject','guidedResearchQuestion','guidedPercentageUnit','guidedAggregate','guidedRankUnit','guidedMeasureField','guidedBreakdown','guidedBreakdownColumn','guidedDisplay','guidedSort'].forEach(id=>{ if(els[id]) els[id].addEventListener(els[id].tagName==='SELECT'?'change':'input',activateGuidedResearch); });
  if(els.guidedResearchTitle) els.guidedResearchTitle.addEventListener('input',()=>{ state.editingGuidedResearchActive=true; els.researchTitleInput.value=els.guidedResearchTitle.value; updateGuidedResearchUi(); });
  if(els.exportResearchBtn) els.exportResearchBtn.onclick=exportResearchConfig;
  if(els.renderAllResearchBtn) els.renderAllResearchBtn.onclick=renderAllResearchItems;
  if(els.buildResearchIndexBtn) els.buildResearchIndexBtn.onclick=async()=>{ showProgress('Preparing only sources used by saved Research items...',4); const prepared=await ensureResearchItemsExecutionIndexes(state.researchItems||[],{start:4,end:96,showProgress:true}); updateResearchCacheBadge(); setResearchCanvasStatus(`${prepared.sources.length.toLocaleString()} used source${prepared.sources.length===1?'':'s'} prepared in ${prepared.totalMs.toLocaleString()} ms.`); hideProgress(); };
  if(els.clearResearchCacheBtn) els.clearResearchCacheBtn.onclick=()=>{ clearResearchComputedCaches('manual clear'); setResearchCanvasStatus('Cached Research results cleared. The fast source index remains available until data changes.'); };
  if(els.clearResearchRenderedBtn) els.clearResearchRenderedBtn.onclick=clearStoredResearchRenderedResults;
  if(els.stopResearchRenderBtn) els.stopResearchRenderBtn.onclick=()=>cancelResearchRenderAll('Stopping after the current safe checkpoint...');
  if(els.newMetricBtn) els.newMetricBtn.onclick=()=>openMetricEditor('');
  if(els.metricSearchInput) els.metricSearchInput.oninput=()=>renderMetricList();
  if(els.metricSourceSelect) els.metricSourceSelect.onchange=()=>{ const chosen=els.metricSourceSelect.value; refreshMetricDatalist(); if(chosen) els.metricSourceSelect.value=chosen; state.editingMetricGear={...researchGearDefault()}; state.editingMetricRules=(state.editingMetricRules||[]).map(r=>({...r,gear:{...researchGearDefault()},selectedValues:[]})); renderMetricRules(); validateMetricNumeric(); };
  if(els.metricModeSelect) els.metricModeSelect.onchange=handleMetricModeOrRangeChange;
  if(els.metricWithinUseRange) els.metricWithinUseRange.onchange=handleMetricModeOrRangeChange;
  if(els.metricFieldInput) els.metricFieldInput.oninput=validateMetricNumeric;
  if(els.metricPercentOfField) els.metricPercentOfField.oninput=validateMetricNumeric;
  if(el('previewMetricFoundBtn')) el('previewMetricFoundBtn').onclick=renderMetricFoundPreview;
  if(els.metricFieldGearBtn) els.metricFieldGearBtn.onclick=openMetricValuePicker; if(els.metricFieldInput) els.metricFieldInput.oninput=()=>{ const box=el('metricFoundPreview'); if(box) box.classList.add('hidden'); validateMetricNumeric(); attachModelReferencePicker(els.metricEditorModal); };
  if(els.addMetricAndBtn) els.addMetricAndBtn.onclick=()=>{state.editingMetricRules.push({join:'AND',op:'is'});renderMetricRules();};
  if(els.addMetricOrBtn) els.addMetricOrBtn.onclick=()=>{state.editingMetricRules.push({join:'OR',op:'is'});renderMetricRules();};
  if(els.saveMetricBtn) els.saveMetricBtn.onclick=()=>saveMetricFromEditor(false);
  if(els.saveExitMetricBtn) els.saveExitMetricBtn.onclick=()=>saveMetricFromEditor(true);
  if(els.deleteMetricBtn) els.deleteMetricBtn.onclick=async ()=>{ const idv=els.metricEditId.value; if(idv&&confirm('Delete this metric?')){ const prev=state.metrics; state.metrics=state.metrics.filter(m=>m.id!==idv); const ok=await saveMetrics(); if(ok){ renderMetricList(); closeModal('metricEditorModal'); } else state.metrics=prev; }};
  if(els.exportMetricsBtn) els.exportMetricsBtn.onclick=exportMetricsConfig;
  if(els.importMetricsFile) els.importMetricsFile.onchange=async e=>{ const f=e.target.files[0]; if(!f) return; try{ await importMetricsConfig(await f.text()); }catch(err){ alert('Metric import failed.'); } e.target.value=''; };
  if(els.importResearchFile) els.importResearchFile.onchange=async e=>{ const f=e.target.files[0]; if(!f) return; try{ await importResearchConfig(await f.text()); }catch(err){ console.error(err); alert('Research import failed. Choose a valid TXT/JSON export.'); } e.target.value=''; };
  if(els.createOrgBtn) els.createOrgBtn.onclick=createOrg;
  if(els.saveOrgBtn) els.saveOrgBtn.onclick=()=>{ const o=activeOrg(); if(!o) return createOrg(); o.name=(els.orgNameInput.value||'New Org').trim(); o.updatedAt=new Date().toISOString(); saveOrgs(); renderOrgBuilder(); };
  if(els.duplicateOrgBtn) els.duplicateOrgBtn.onclick=()=>{ const o=activeOrg(); if(!o) return; const cp=normalizeOrg({...clonePlain(o),id:id(),name:o.name+' copy',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()}); state.orgs.push(cp); state.activeOrgId=cp.id; saveOrgs(); renderOrgBuilder(); };
  if(els.deleteOrgBtn) els.deleteOrgBtn.onclick=()=>{ const o=activeOrg(); if(o&&confirm(`Delete org "${o.name}"?`)){ state.orgs=state.orgs.filter(x=>x.id!==o.id); state.activeOrgId=state.orgs[0]?.id||''; saveOrgs(); renderOrgBuilder(); } };
  if(els.exportOrgsBtn) els.exportOrgsBtn.onclick=exportOrgs;
  if(els.importOrgsFile) els.importOrgsFile.onchange=async e=>{ const f=e.target.files[0]; if(!f) return; try{ importOrgs(await f.text()); }catch(err){ alert('Org import failed.'); } e.target.value=''; };
  if(els.orgSearchInput) els.orgSearchInput.oninput=()=>{ state.orgSearch=els.orgSearchInput.value; renderOrgBuilder(); };
  if(els.orgCoachSearchInput) els.orgCoachSearchInput.oninput=()=>{ state.orgCoachSearch=els.orgCoachSearchInput.value; renderOrgBuilder(); };
  if(els.selectVisibleOrgCoachesBtn) els.selectVisibleOrgCoachesBtn.onclick=()=>{ const o=activeOrg(); if(!o) return; const next=new Set(o.coachNames||[]); knownCoachNames().filter(c=>!state.orgCoachSearch||normalizeOrgName(c).includes(normalizeOrgName(state.orgCoachSearch))).forEach(c=>next.add(c)); o.coachNames=[...next].sort((a,b)=>a.localeCompare(b)); saveOrgs(); renderOrgBuilder(); };
  if(els.clearOrgCoachesBtn) els.clearOrgCoachesBtn.onclick=()=>{ const o=activeOrg(); if(!o) return; o.coachNames=[]; saveOrgs(); renderOrgBuilder(); };
  if(els.clearResearchBtn) els.clearResearchBtn.onclick=clearResearchItemsWithConfirm;
  if(els.researchSource) els.researchSource.onchange=()=>{ populateResearchFieldSelectors({}); populateResearchTypedMeasurePicker(currentResearchItemFromEditor()); renderResearchTypedMeasureMeta(); if(state.editingPercentBuilder&&state.editingPercentBuilder.fromMode!=='custom_expression') state.editingPercentBuilder.qualifierSource=els.researchSource.value; renderResearchColumnsEditor(); renderPercentBuilderEditor(currentResearchItemFromEditor()); scheduleResearchJoinPreview(); updateResearchBuilderVisibility(); };
  if(els.researchOutputType) els.researchOutputType.onchange=()=>{ const t=els.researchOutputType.value, graph=['line','bar','scatter','histogram','heatmap','box','pie'].includes(t); if(graph&&els.researchShowValues) els.researchShowValues.checked=true; if(t==='line'&&els.researchUseDots) els.researchUseDots.checked=true; if(t==='heatmap'&&els.researchUseSecondaryGroup) els.researchUseSecondaryGroup.value='yes'; if(t==='scatter'&&els.researchAnalysisGrain?.value==='auto') els.researchAnalysisGrain.value='representatives'; if(t==='histogram'&&els.researchValueMode) els.researchValueMode.value='count'; if((graph||els.researchUseSecondaryGroup?.value==='yes')&&els.researchShowLegend) els.researchShowLegend.checked=true; populateResearchTypedMeasurePicker(currentResearchItemFromEditor()); validateResearchEditor(); updateResearchBuilderVisibility(); };
  if(els.researchAnalysisGrain) els.researchAnalysisGrain.onchange=()=>{ populateResearchTypedMeasurePicker(currentResearchItemFromEditor()); renderResearchTypedMeasureMeta(); scheduleResearchJoinPreview(); validateResearchEditor(); };
  if(els.researchCrossSourceJoin) els.researchCrossSourceJoin.onchange=()=>{ scheduleResearchJoinPreview(); validateResearchEditor(); };
  if(els.researchUnmatchedBehavior) els.researchUnmatchedBehavior.onchange=scheduleResearchJoinPreview;
  [els.researchGroupField,els.researchSecondaryGroupField,els.researchPanelField].forEach(input=>{ if(input) input.addEventListener('input',debounce(()=>{ scheduleResearchJoinPreview(); validateResearchEditor(); },160)); });
  if(els.researchValueMode) els.researchValueMode.onchange=updateResearchBuilderVisibility; if(els.researchWithinUseRange) els.researchWithinUseRange.onchange=updateResearchBuilderVisibility; if(els.researchGroupMultiAdd) els.researchGroupMultiAdd.onchange=updateResearchBuilderVisibility; if(els.researchUseSecondaryGroup) els.researchUseSecondaryGroup.onchange=()=>{ if(els.researchUseSecondaryGroup.value==='yes'&&els.researchShowLegend) els.researchShowLegend.checked=true; updateResearchBuilderVisibility(); }; if(els.researchValueField) els.researchValueField.oninput=validateResearchEditor; if(els.researchPercentOfField) els.researchPercentOfField.oninput=validateResearchEditor;
  if(els.researchModelSelect) els.researchModelSelect.onchange=()=>populateResearchCriteria();
  if(els.addResearchFilterBtn) els.addResearchFilterBtn.onclick=()=>{ state.editingResearchFilters.push({include:'include',op:'contains'}); renderResearchFiltersEditor(); };
  if(els.addResearchColumnBtn) els.addResearchColumnBtn.onclick=()=>{ state.editingResearchColumns.push({label:'Value',mode:'count',field:''}); renderResearchColumnsEditor(); }; if(els.researchGroupMultiAdd) els.researchGroupMultiAdd.onchange=renderResearchGroupAxisItemsEditor; if(els.researchGroupMultiAddBtn) els.researchGroupMultiAddBtn.onclick=()=>{ const v=(els.researchGroupMultiAddInput.value||'').trim(); if(!v) return; state.editingResearchGroupAxisItems=state.editingResearchGroupAxisItems||[]; state.editingResearchGroupAxisItems.push({id:id(),expression:v,label:'',conditionResult:'true'}); els.researchGroupMultiAddInput.value=''; renderResearchGroupAxisItemsEditor(); };
  if(els.previewResearchFoundBtn) els.previewResearchFoundBtn.onclick=()=>{ if(state.editingGuidedResearchActive) syncGuidedResearchToAdvanced(); const validation=state.editingGuidedResearchActive?validateGuidedResearch(false):{ok:true,errors:[]}; if(!validation.ok){ alert(validation.errors.join('\n')); return; } renderResearchFoundPreview(); };
  if(els.saveResearchItemBtn) els.saveResearchItemBtn.onclick=saveResearchItemFromEditor;
  els.retailFile.onchange=e=>{const f=e.target.files[0]; if(f) loadRetailFile(f);};
  if(els.rosterReassignmentArea) els.rosterReassignmentArea.onchange=()=>{ clearRosterReassignmentPreview(); restoreImportFileLabels(); };
  if(els.rosterReassignmentFile) els.rosterReassignmentFile.onchange=e=>{ const f=e.target.files[0]; if(f) previewRosterReassignmentFile(f); };
  if(els.applyRosterReassignmentBtn) els.applyRosterReassignmentBtn.onclick=applyRosterReassignment;
  if(els.applyRosterReassignmentFootBtn) els.applyRosterReassignmentFootBtn.onclick=applyRosterReassignment;
  if(els.clearRosterReassignmentBtn) els.clearRosterReassignmentBtn.onclick=clearRosterReassignmentPreview;
  els.referralFile.onchange=e=>{const f=e.target.files[0]; if(f) loadReferralFile(f);};
  els.qaFile.onchange=e=>{const f=e.target.files[0]; if(f) loadQAFile(f);};
  if(els.qaDirectFile) els.qaDirectFile.onchange=e=>{const f=e.target.files[0]; if(f) loadDirectQAFile(f);};
  if(els.clearQADirectFileBtn) els.clearQADirectFileBtn.onclick=clearDirectQAFile;
  els.checklistFile.onchange=e=>{const f=e.target.files[0]; if(f) loadChecklistFile(f);};
  if(els.documentedCoachingFile) els.documentedCoachingFile.onchange=e=>{const f=e.target.files[0]; if(f) loadChecklistLikeFile(f,'documented_coaching');};
  if(els.compCallsFile) els.compCallsFile.onchange=e=>{const f=e.target.files[0]; if(f) loadChecklistLikeFile(f,'comp_calls');};
  if(els.packagedFile) els.packagedFile.onchange=e=>{const f=e.target.files[0]; if(f) loadPackagedFile(f);};
  els.createModelBtn.onclick=()=>openEditModel(null);
  els.exportModelsBtn.onclick=()=>downloadText('all_star_models.txt', serializeModelsForExport(state.models||[]));
  els.importModelsFile.onchange=async e=>{const f=e.target.files[0]; if(!f) return; const text=await f.text(); try{parseModelsImportText(text).forEach(upsertModel); saveModels(); renderEditModelSafe(); renderMassHeaderCheck();}catch(err){console.error(err); alert('Import failed. Make sure this is a model TXT/JSON export.');} e.target.value='';};
  els.addCriterionBtn.onclick=()=>{syncEditModelFields(); state.editModel.criteria.push(emptyCriterion()); renderEditModel();};
  els.cancelModelBtn.onclick=els.cancelModelTopBtn.onclick=()=>closeModal('editModelModal');
  els.saveModelBtn.onclick=()=>saveEditModel(false);
  els.saveExitModelBtn.onclick=()=>saveEditModel(true);
  els.modelNameInput.oninput=()=>{ if(state.editModel) state.editModel.name=els.modelNameInput.value; };
  els.modelTypeInput.onchange=()=>{ if(state.editModel) state.editModel.type=els.modelTypeInput.value; };
  els.modelTiebreakerInput.onchange=()=>{ if(state.editModel) state.editModel.tiebreaker=els.modelTiebreakerInput.value; };
  if(els.runSingleTab) els.runSingleTab.onclick=()=>applyRunMode('single');
  if(els.runMultiTab) els.runMultiTab.onclick=()=>applyRunMode('multi');
  if(els.runModelSelect) els.runModelSelect.onchange=()=>{ updateRunQADateField(); setDefaultRunDates(); renderTeamSelect(); updateMultiRunSummary(); saveRunSettings(); beginSelectedModelPreparation(); };
  if(els.runStartDate) els.runStartDate.onchange=()=>{ updateMultiRunSummary(); saveRunSettings(); };
  if(els.runEndDate) els.runEndDate.onchange=()=>{ updateMultiRunSummary(); saveRunSettings(); };
  if(els.runViewSelect) els.runViewSelect.onchange=()=>{ updateMultiRunSummary(); saveRunSettings(); };
  if(els.hideNoScoreReps) els.hideNoScoreReps.onchange=()=>{ if(els.hideNoScoreThreshold) els.hideNoScoreThreshold.classList.toggle('hidden', !els.hideNoScoreReps.checked); saveRunSettings(); };
  if(els.hideNoScoreThreshold) els.hideNoScoreThreshold.onchange=saveRunSettings;
  if(els.rankRepresentativesWithinTeam) els.rankRepresentativesWithinTeam.onchange=()=>{ updateMultiRunSummary(); saveRunSettings(); };
  if(els.runQADateSelect) els.runQADateSelect.onchange=()=>{ setDefaultRunDates(); saveRunSettings(); beginSelectedModelPreparation(); };
  if(els.runQATeamScoreMode) els.runQATeamScoreMode.onchange=()=>{ saveRunSettings(); beginSelectedModelPreparation(); };
  if(els.runOrgSearchInput) els.runOrgSearchInput.oninput=()=>{ state.runOrgSearch=els.runOrgSearchInput.value; renderRunOrgSelect(); };
  if(els.clearRunOrgsBtn) els.clearRunOrgsBtn.onclick=()=>{ state.runIncludeOrgs.clear(); state.runExcludeOrgs.clear(); renderRunOrgSelect(); saveRunSettings(); };
  if(els.multiRunOrgSearch) els.multiRunOrgSearch.oninput=()=>{ state.multiRunOrgSearch=els.multiRunOrgSearch.value; renderMultiRunOrgSelect(); };
  if(els.multiRunSelectVisibleBtn) els.multiRunSelectVisibleBtn.onclick=()=>{ visibleMultiRunOrgs().forEach(o=>state.multiRunOrgIds.add(o.id)); renderMultiRunOrgSelect(); saveRunSettings(); };
  if(els.multiRunClearBtn) els.multiRunClearBtn.onclick=()=>{ state.multiRunOrgIds.clear(); renderMultiRunOrgSelect(); saveRunSettings(); };
  els.teamSearchInput.oninput=()=>{ syncTeamSelectionsFromDom(); state.teamSearch=els.teamSearchInput.value; renderTeamSelect(); };
  els.addVisibleTeamsBtn.onclick=()=>setVisibleTeamsChecked(true);
  els.removeVisibleTeamsBtn.onclick=()=>setVisibleTeamsChecked(false);
  els.selectAllTeamsBtn.onclick=()=>{ state.teamSelectionInitialized=true; state.selectedTeams=new Set(runTeamNames()); renderTeamSelect(); saveRunSettings(); };
  els.clearTeamsBtn.onclick=()=>{ state.teamSelectionInitialized=true; state.selectedTeams.clear(); renderTeamSelect(); saveRunSettings(); };
  if(els.teamManagerSearch) els.teamManagerSearch.oninput=debounce(()=>renderTeamsImportedModal(),180);
  if(els.teamRepSearch) els.teamRepSearch.oninput=debounce(()=>{ if(state.activeTeam) renderCachedTeamDetails(state.activeTeam); },180);
  if(els.selectAllTeamRepsBtn) els.selectAllTeamRepsBtn.onclick=()=>setVisibleTeamRepsChecked(true);
  if(els.unselectAllTeamRepsBtn) els.unselectAllTeamRepsBtn.onclick=()=>setVisibleTeamRepsChecked(false);
  if(els.moveTeamBtn) els.moveTeamBtn.onclick=moveSelectedRepsToTeam;
  if(els.teamConnectThreshold) els.teamConnectThreshold.oninput=renderTeamConnectionPanel;
  if(els.connectVisibleRepMatchesBtn) els.connectVisibleRepMatchesBtn.onclick=()=>connectRepMatches(true);
  if(els.connectAllRepMatchesBtn) els.connectAllRepMatchesBtn.onclick=()=>connectRepMatches(false);
  els.executeRunBtn.onclick=buildRun;

}


let allStarRegressionTestsLoadPromise=null;
function loadAllStarRegressionTests(){
  if(typeof window.runAllStarRegressionTests==='function') return Promise.resolve(window.runAllStarRegressionTests);
  if(allStarRegressionTestsLoadPromise) return allStarRegressionTestsLoadPromise;
  allStarRegressionTestsLoadPromise=new Promise((resolve,reject)=>{
    const script=document.createElement('script');
    if(typeof window.__ALLSTAR_REGRESSION_TESTS_SOURCE__==='string') script.text=window.__ALLSTAR_REGRESSION_TESTS_SOURCE__;
    else script.src='tests/regression-tests.js';
    script.onload=()=>typeof window.runAllStarRegressionTests==='function'?resolve(window.runAllStarRegressionTests):reject(new Error('Regression tests loaded without exposing runAllStarRegressionTests().'));
    script.onerror=()=>reject(new Error('Could not load tests/regression-tests.js. Keep the full All-Star folder together.'));
    document.head.appendChild(script);
    if(script.text&&typeof window.runAllStarRegressionTests==='function') resolve(window.runAllStarRegressionTests);
  });
  return allStarRegressionTestsLoadPromise;
}
window.loadAllStarRegressionTests=loadAllStarRegressionTests;
if(new URLSearchParams(window.location.search).get('debug')==='1'){
  loadAllStarRegressionTests().then(()=>console.info('[All Star] Regression tests loaded. Run await runAllStarRegressionTests() when ready.')).catch(err=>console.error('[All Star] Regression tests could not load',err));
}

window.addEventListener('pagehide',()=>{ flushImportCacheSave('pagehide flush').catch(err=>console.warn('[Import Cache] pagehide flush failed',err)); });
document.addEventListener('visibilitychange',()=>{ if(document.visibilityState==='hidden') flushImportCacheSave('visibilitychange flush').catch(err=>console.warn('[Import Cache] visibility flush failed',err)); });
loadModels(); loadRepAliases(); loadResearchItems(); loadPdfOptions(); loadOrgs(); wire(); loadMetrics().then(()=>{ refreshMetricDatalist(); }).catch(err=>console.warn('[Research Metrics] Startup load failed',err)); renderCustomSourcesList(); renderCategorizedSummary(); renderModelList(); populateRunModels(); setStatus(); state.importCacheStartupPromise=loadImportCacheOnStartup();
