/* Built-in configuration supplied by Sean Pereksta. Preserve complete criteria and mappings. */
'use strict';
const ALLSTAR_DEFAULT_MODELS = {
  "version": 4,
  "exportedAt": "2026-09-09T17:16:32.238Z",
  "models": [
    {
      "id": "mmsdnksn57fqi3b",
      "name": "QA Score",
      "type": "both",
      "tiebreaker": "overallScore",
      "criteria": [
        {
          "id": "mmqtvg5281m1ukr",
          "name": "QA Score %",
          "source": "qa",
          "calcType": "qaScore",
          "audience": "both",
          "scoreType": "rank",
          "direction": "higher",
          "weight": "1",
          "format": "pct",
          "missingRank": 999,
          "missingPoints": 0,
          "zeroCanWin": false,
          "minimumMonitors": 0,
          "filters": [],
          "minimumEnabled": false,
          "minimum": 0,
          "autofailThreshold": 1,
          "autofailOperator": "greaterEqual",
          "leftSource": "qa",
          "rightSource": "qa",
          "customSource": "qa",
          "aggregate": "sum",
          "operator": "divide",
          "checkOperator": "contains",
          "points": 1,
          "column": "",
          "leftColumn": "",
          "rightColumn": "",
          "checkDateColumn": "",
          "checkColumn": "",
          "expression": "",
          "checkText": "",
          "rowPullConditions": [
            {
              "id": "mmqtvg528rxxfnu",
              "connector": "base",
              "column": "",
              "dateColumn": "",
              "operator": "contains",
              "phrasesText": ""
            }
          ],
          "qaColumns": {},
          "checkValueType": "text",
          "withinUseRange": false,
          "withinDays": "",
          "withinRangeMin": "",
          "withinRangeMax": "",
          "withinCompareColumn": "",
          "trueValueEnabled": false,
          "trueValueSource": "",
          "trueValueColumn": "",
          "lookupMatchColumn": "",
          "lookupReturnColumn": "",
          "lookupDateColumn": ""
        }
      ],
      "sourceSettings": {
        "retail_sv2": {
          "headerRow": 4,
          "startCol": 3,
          "columns": {
            "team": "",
            "date": "Agent_HireDate",
            "useDateColumn": true,
            "skipTeamBuild": false,
            "nameMode": "firstLast",
            "fullName": "",
            "firstName": "Agent_Firstname",
            "lastName": "Agent_Surname",
            "convertLastFirst": false
          },
          "sheetName": "sv2",
          "manualHeaders": []
        },
        "retail_wiper": {
          "headerRow": 1,
          "startCol": 1,
          "columns": {
            "team": "",
            "date": "",
            "useDateColumn": null,
            "skipTeamBuild": false,
            "nameMode": "auto",
            "fullName": "",
            "firstName": "",
            "lastName": "",
            "convertLastFirst": false
          },
          "sheetName": "sv2 wiper",
          "manualHeaders": []
        },
        "referral_sv2": {
          "headerRow": 1,
          "startCol": 1,
          "columns": {
            "team": "",
            "date": "",
            "useDateColumn": false,
            "skipTeamBuild": true,
            "nameMode": "firstLast",
            "fullName": "",
            "firstName": "Agent_Firstname",
            "lastName": "Agent_Surname",
            "convertLastFirst": false
          },
          "sheetName": "sv2",
          "manualHeaders": []
        },
        "referral_wiper": {
          "headerRow": 1,
          "startCol": 1,
          "columns": {
            "team": "Team_Name",
            "date": "",
            "useDateColumn": false,
            "skipTeamBuild": false,
            "nameMode": "firstLast",
            "fullName": "",
            "firstName": "FIRST_NAME",
            "lastName": "LAST_NAME",
            "convertLastFirst": false
          },
          "sheetName": "sv2 wipers",
          "manualHeaders": []
        },
        "qa": {
          "headerRow": 1,
          "startCol": 1,
          "sheetName": "Genesys Evaluation Score",
          "manualHeaders": [],
          "columns": {
            "agent": "Agent Name",
            "team": "Team",
            "score": "Score %",
            "interactionDate": "Interaction Start Time",
            "assignedDate": "Assigned Date",
            "date": "Interaction Start Time",
            "useDateColumn": true,
            "skipTeamBuild": false,
            "nameMode": "full",
            "fullName": "Agent Name",
            "firstName": "",
            "lastName": "",
            "convertLastFirst": false
          }
        },
        "checklist": {
          "headerRow": 1,
          "startCol": 1,
          "sheetName": "All Items",
          "manualHeaders": [],
          "columns": {
            "rep": "Associate Name",
            "team": "Coach Assigned",
            "date": "",
            "useDateColumn": null,
            "skipTeamBuild": false,
            "nameMode": "full",
            "fullName": "Associate Name",
            "firstName": "",
            "lastName": "",
            "convertLastFirst": false
          }
        },
        "documented_coaching": {
          "headerRow": 1,
          "startCol": 1,
          "sheetName": "Myone2view",
          "manualHeaders": [],
          "columns": {
            "rep": "Associate name",
            "team": "Job Coach",
            "date": "",
            "useDateColumn": null,
            "skipTeamBuild": false,
            "nameMode": "full",
            "fullName": "Associate name",
            "firstName": "",
            "lastName": "",
            "convertLastFirst": false
          }
        },
        "comp_calls": {
          "headerRow": 1,
          "startCol": 1,
          "sheetName": "Compliments 2026",
          "manualHeaders": [],
          "columns": {
            "rep": "CSR/SSR Name (This is the person being complimented)",
            "team": "CSR Team/Coach",
            "date": "Date of Call",
            "useDateColumn": true,
            "skipTeamBuild": false,
            "text": "Compliment",
            "nameMode": "full",
            "fullName": "CSR/SSR Name (This is the person being complimented)",
            "firstName": "",
            "lastName": "",
            "convertLastFirst": false
          }
        }
      }
    },
    {
      "id": "mmqv1pob0jjg243",
      "name": "Referral All Star Report",
      "type": "both",
      "tiebreaker": "overallScore",
      "criteria": [
        {
          "id": "mmqv1puk5hfhvn5",
          "name": "Wiper Rate",
          "source": "referral_wiper",
          "calcType": "custom",
          "audience": "both",
          "scoreType": "rank",
          "direction": "higher",
          "weight": "2",
          "format": "pct",
          "missingRank": 999,
          "missingPoints": 0,
          "zeroCanWin": false,
          "minimumMonitors": 0,
          "column": "",
          "aggregate": "sum",
          "leftSource": "referral_wiper",
          "leftColumn": "",
          "operator": "divide",
          "rightSource": "referral_wiper",
          "rightColumn": "",
          "customSource": "referral_wiper",
          "expression": "[Accepted]/([Accepted]+[Declined])",
          "checkDateColumn": "",
          "checkColumn": "",
          "checkOperator": "contains",
          "checkText": "",
          "filters": [
            {
              "id": "mmqv1qoz8vyydb2",
              "action": "include",
              "mode": "include",
              "operator": "greaterThan",
              "source": "referral_wiper",
              "column": "",
              "values": [],
              "value": "10",
              "value2": "",
              "targetSource": "qa",
              "targetDateColumn": "",
              "targetValueColumn": "",
              "targetOp": "contains",
              "targetValue": "",
              "windowMode": "days",
              "dayWindow": "0",
              "dynamicColumn": true,
              "columnExpression": "[Accepted]+[Declined]",
              "dynamic": false,
              "expression": "",
              "rangeStart": "",
              "rangeEnd": ""
            }
          ],
          "minimumEnabled": false,
          "minimum": 0,
          "points": 1,
          "autofailThreshold": 1,
          "autofailOperator": "greaterEqual",
          "rowPullConditions": [
            {
              "id": "mmqv1puk72abr44",
              "connector": "base",
              "column": "",
              "dateColumn": "",
              "operator": "contains",
              "phrasesText": ""
            }
          ],
          "qaColumns": {},
          "checkValueType": "text",
          "withinUseRange": false,
          "withinDays": "",
          "withinRangeMin": "",
          "withinRangeMax": "",
          "withinCompareColumn": "",
          "trueValueEnabled": false,
          "trueValueSource": "",
          "trueValueColumn": "",
          "lookupMatchColumn": "",
          "lookupReturnColumn": "",
          "lookupDateColumn": ""
        },
        {
          "id": "mmqv1r0f4k82kle",
          "name": "ITAC",
          "source": "referral_sv2",
          "calcType": "multi",
          "audience": "both",
          "scoreType": "rank",
          "direction": "higher",
          "weight": "1",
          "format": "pct",
          "missingRank": 999,
          "missingPoints": 0,
          "zeroCanWin": false,
          "minimumMonitors": 0,
          "column": "",
          "aggregate": "sum",
          "leftSource": "referral_sv2",
          "leftColumn": "Cash Apps",
          "operator": "divide",
          "rightSource": "referral_sv2",
          "rightColumn": "Cash Opps",
          "customSource": "referral_sv2",
          "expression": "",
          "checkDateColumn": "",
          "checkColumn": "",
          "checkOperator": "contains",
          "checkText": "",
          "filters": [
            {
              "id": "mmqv1tg3qkfxgvp",
              "action": "include",
              "mode": "include",
              "operator": "greaterThan",
              "source": "referral_sv2",
              "column": "Cash Opps",
              "values": [],
              "value": "5",
              "value2": "",
              "targetSource": "qa",
              "targetDateColumn": "",
              "targetValueColumn": "",
              "targetOp": "contains",
              "targetValue": "",
              "windowMode": "days",
              "dayWindow": "0",
              "dynamic": false,
              "expression": "",
              "dynamicColumn": false,
              "columnExpression": "",
              "rangeStart": "",
              "rangeEnd": ""
            }
          ],
          "minimumEnabled": false,
          "minimum": 0,
          "points": 1,
          "autofailThreshold": 1,
          "autofailOperator": "greaterEqual",
          "rowPullConditions": [
            {
              "id": "mmqv1r0f6dms3x7",
              "connector": "base",
              "column": "",
              "dateColumn": "",
              "operator": "contains",
              "phrasesText": ""
            }
          ],
          "qaColumns": {},
          "checkValueType": "text",
          "withinUseRange": false,
          "withinDays": "",
          "withinRangeMin": "",
          "withinRangeMax": "",
          "withinCompareColumn": "",
          "trueValueEnabled": false,
          "trueValueSource": "",
          "trueValueColumn": "",
          "lookupMatchColumn": "",
          "lookupReturnColumn": "",
          "lookupDateColumn": ""
        },
        {
          "id": "mmqv1tqh0feknl3",
          "name": "QA Score",
          "source": "qa",
          "calcType": "qaScore",
          "audience": "both",
          "scoreType": "rank",
          "direction": "higher",
          "weight": "1",
          "format": "pct",
          "missingRank": 999,
          "missingPoints": 0,
          "zeroCanWin": false,
          "minimumMonitors": 1,
          "column": "",
          "aggregate": "sum",
          "leftSource": "qa",
          "leftColumn": "",
          "operator": "divide",
          "rightSource": "qa",
          "rightColumn": "",
          "customSource": "qa",
          "expression": "",
          "checkDateColumn": "",
          "checkColumn": "",
          "checkOperator": "contains",
          "checkText": "",
          "filters": [],
          "minimumEnabled": false,
          "minimum": 0,
          "points": 1,
          "autofailThreshold": 1,
          "autofailOperator": "greaterEqual",
          "rowPullConditions": [
            {
              "id": "mmqv1tqh38if62q",
              "connector": "base",
              "column": "",
              "dateColumn": "",
              "operator": "contains",
              "phrasesText": ""
            }
          ],
          "qaColumns": {},
          "checkValueType": "text",
          "withinUseRange": false,
          "withinDays": "",
          "withinRangeMin": "",
          "withinRangeMax": "",
          "withinCompareColumn": "",
          "trueValueEnabled": false,
          "trueValueSource": "",
          "trueValueColumn": "",
          "lookupMatchColumn": "",
          "lookupReturnColumn": "",
          "lookupDateColumn": ""
        }
      ],
      "sourceSettings": {
        "retail_sv2": {
          "headerRow": 4,
          "startCol": 3,
          "columns": {
            "team": "",
            "date": "Agent_HireDate",
            "useDateColumn": true,
            "skipTeamBuild": false,
            "nameMode": "firstLast",
            "fullName": "",
            "firstName": "Agent_Firstname",
            "lastName": "Agent_Surname",
            "convertLastFirst": false
          },
          "sheetName": "sv2",
          "manualHeaders": []
        },
        "retail_wiper": {
          "headerRow": 1,
          "startCol": 1,
          "columns": {
            "team": "",
            "date": "",
            "useDateColumn": null,
            "skipTeamBuild": false,
            "nameMode": "auto",
            "fullName": "",
            "firstName": "",
            "lastName": "",
            "convertLastFirst": false
          }
        },
        "referral_sv2": {
          "headerRow": 1,
          "startCol": 1,
          "columns": {
            "team": "",
            "date": "",
            "useDateColumn": false,
            "skipTeamBuild": true,
            "nameMode": "firstLast",
            "fullName": "",
            "firstName": "Agent_Firstname",
            "lastName": "Agent_Surname",
            "convertLastFirst": false
          },
          "sheetName": "sv2",
          "manualHeaders": []
        },
        "referral_wiper": {
          "headerRow": 1,
          "startCol": 1,
          "columns": {
            "team": "Team_Name",
            "date": "",
            "useDateColumn": false,
            "skipTeamBuild": false,
            "nameMode": "firstLast",
            "fullName": "",
            "firstName": "FIRST_NAME",
            "lastName": "LAST_NAME",
            "convertLastFirst": false
          },
          "sheetName": "sv2 wipers",
          "manualHeaders": []
        },
        "qa": {
          "headerRow": 1,
          "startCol": 1,
          "sheetName": "",
          "manualHeaders": [],
          "columns": {
            "agent": "Agent Name",
            "team": "Team",
            "score": "Score %",
            "interactionDate": "Interaction Start Time",
            "assignedDate": "Assigned Date",
            "date": "Interaction Start Time",
            "useDateColumn": true,
            "skipTeamBuild": false,
            "nameMode": "full",
            "fullName": "Agent Name",
            "firstName": "",
            "lastName": "",
            "convertLastFirst": false
          }
        },
        "checklist": {
          "headerRow": 1,
          "startCol": 1,
          "sheetName": "",
          "manualHeaders": [],
          "columns": {
            "rep": "Associate Name",
            "team": "Coach Assigned",
            "date": "",
            "useDateColumn": null,
            "skipTeamBuild": false,
            "nameMode": "full",
            "fullName": "Associate Name",
            "firstName": "",
            "lastName": "",
            "convertLastFirst": false
          }
        },
        "documented_coaching": {
          "headerRow": 1,
          "startCol": 1,
          "sheetName": "",
          "manualHeaders": [],
          "columns": {
            "rep": "Associate name",
            "team": "Job Coach",
            "date": "",
            "useDateColumn": null,
            "skipTeamBuild": false,
            "nameMode": "full",
            "fullName": "Associate name",
            "firstName": "",
            "lastName": "",
            "convertLastFirst": false
          }
        },
        "comp_calls": {
          "headerRow": 1,
          "startCol": 1,
          "sheetName": "",
          "manualHeaders": [],
          "columns": {
            "rep": "CSR/SSR Name (This is the person being complimented)",
            "team": "CSR Team/Coach",
            "date": "Date of Call",
            "useDateColumn": true,
            "skipTeamBuild": false,
            "text": "Compliment",
            "nameMode": "full",
            "fullName": "CSR/SSR Name (This is the person being complimented)",
            "firstName": "",
            "lastName": "",
            "convertLastFirst": false
          }
        }
      }
    },
    {
      "id": "mmqzm1h8mr90drm",
      "name": "Retail Scores",
      "type": "both",
      "tiebreaker": "overallScore",
      "criteria": [
        {
          "id": "mmqzm1o4d8286qo",
          "name": "Cash Appointment Rate",
          "source": "nondate",
          "calcType": "multi",
          "audience": "both",
          "scoreType": "rank",
          "direction": "higher",
          "weight": "1",
          "format": "pct",
          "missingRank": 999,
          "missingPoints": 0,
          "zeroCanWin": false,
          "minimumMonitors": 0,
          "column": "",
          "aggregate": "sum",
          "leftSource": "nondate",
          "leftColumn": "retail.sv2.cash.apps",
          "operator": "divide",
          "rightSource": "nondate",
          "rightColumn": "retail.sv2.cash.opps",
          "customSource": "nondate",
          "expression": "",
          "checkDateColumn": "",
          "checkColumn": "",
          "checkOperator": "contains",
          "checkText": "",
          "filters": [
            {
              "id": "mmqzm2s4nz2l7fi",
              "action": "include",
              "mode": "include",
              "operator": "greaterThan",
              "source": "nondate",
              "column": "retail.sv2.cash.opps",
              "values": [],
              "value": "10",
              "value2": "",
              "targetSource": "qa",
              "targetDateColumn": "",
              "targetValueColumn": "",
              "targetOp": "contains",
              "targetValue": "",
              "windowMode": "days",
              "dayWindow": "0",
              "dynamic": false,
              "expression": "",
              "dynamicColumn": false,
              "columnExpression": "",
              "rangeStart": "",
              "rangeEnd": ""
            }
          ],
          "minimumEnabled": false,
          "minimum": 0,
          "points": 1,
          "autofailThreshold": 1,
          "autofailOperator": "greaterEqual",
          "rowPullConditions": [
            {
              "id": "mmqzm1o4fcqbvza",
              "connector": "base",
              "column": "",
              "dateColumn": "",
              "operator": "contains",
              "phrasesText": ""
            }
          ],
          "qaColumns": {},
          "checkValueType": "text",
          "withinUseRange": false,
          "withinDays": "",
          "withinRangeMin": "",
          "withinRangeMax": "",
          "withinCompareColumn": "",
          "trueValueEnabled": true,
          "trueValueSource": "retail_team_totals",
          "trueValueColumn": "Consumer Appointment Rate",
          "lookupMatchColumn": "",
          "lookupReturnColumn": "",
          "lookupDateColumn": ""
        },
        {
          "id": "mmqzm339cre38kf",
          "name": "Wiper Rate",
          "source": "nondate",
          "calcType": "custom",
          "audience": "both",
          "scoreType": "rank",
          "direction": "higher",
          "weight": "1",
          "format": "number",
          "missingRank": 999,
          "missingPoints": 0,
          "zeroCanWin": false,
          "minimumMonitors": 0,
          "column": "",
          "aggregate": "sum",
          "leftSource": "nondate",
          "leftColumn": "",
          "operator": "divide",
          "rightSource": "nondate",
          "rightColumn": "",
          "customSource": "nondate",
          "expression": "[retail.wipers.accepted]/([retail.wipers.accepted]+[retail.wipers.declined])",
          "checkDateColumn": "",
          "checkColumn": "",
          "checkOperator": "contains",
          "checkText": "",
          "filters": [],
          "minimumEnabled": false,
          "minimum": 0,
          "points": 1,
          "autofailThreshold": 1,
          "autofailOperator": "greaterEqual",
          "rowPullConditions": [
            {
              "id": "mmqzm339f09xp6j",
              "connector": "base",
              "column": "",
              "dateColumn": "",
              "operator": "contains",
              "phrasesText": ""
            }
          ],
          "qaColumns": {},
          "checkValueType": "text",
          "withinUseRange": false,
          "withinDays": "",
          "withinRangeMin": "",
          "withinRangeMax": "",
          "withinCompareColumn": "",
          "trueValueEnabled": true,
          "trueValueSource": "retail_team_totals",
          "trueValueColumn": "Wiper Rate",
          "lookupMatchColumn": "",
          "lookupReturnColumn": "",
          "lookupDateColumn": ""
        },
        {
          "id": "mmqznj2r8pt7z1j",
          "name": "QA Scores",
          "source": "date",
          "calcType": "qaScore",
          "audience": "both",
          "scoreType": "rank",
          "direction": "higher",
          "weight": "1",
          "format": "number",
          "missingRank": 999,
          "missingPoints": 0,
          "zeroCanWin": false,
          "minimumMonitors": 1,
          "column": "",
          "aggregate": "sum",
          "leftSource": "date",
          "leftColumn": "",
          "operator": "divide",
          "rightSource": "date",
          "rightColumn": "",
          "customSource": "date",
          "expression": "",
          "checkDateColumn": "",
          "checkColumn": "",
          "checkOperator": "contains",
          "checkText": "",
          "filters": [],
          "minimumEnabled": false,
          "minimum": 0,
          "points": 1,
          "autofailThreshold": 1,
          "autofailOperator": "greaterEqual",
          "rowPullConditions": [
            {
              "id": "mmqznj2rb3hjdqh",
              "connector": "base",
              "column": "",
              "dateColumn": "",
              "operator": "contains",
              "phrasesText": ""
            }
          ],
          "qaColumns": {
            "rep": "Representative",
            "team": "Coach",
            "date": "qa.genesys.evaluation.score.assigned.date",
            "score": "qa.genesys.evaluation.score.score.percent"
          },
          "checkValueType": "text",
          "withinUseRange": false,
          "withinDays": "",
          "withinRangeMin": "",
          "withinRangeMax": "",
          "withinCompareColumn": "",
          "trueValueEnabled": false,
          "trueValueSource": "retail_team_totals",
          "trueValueColumn": "",
          "lookupMatchColumn": "",
          "lookupReturnColumn": "",
          "lookupDateColumn": ""
        },
        {
          "id": "mmqzoc0s37bv93p",
          "name": "Corrective",
          "source": "date",
          "calcType": "checklistCount",
          "audience": "rep",
          "scoreType": "rank",
          "direction": "higher",
          "weight": "autofail",
          "format": "number",
          "missingRank": 999,
          "missingPoints": 0,
          "zeroCanWin": false,
          "minimumMonitors": 0,
          "column": "",
          "aggregate": "sum",
          "leftSource": "date",
          "leftColumn": "",
          "operator": "divide",
          "rightSource": "date",
          "rightColumn": "",
          "customSource": "date",
          "expression": "",
          "checkDateColumn": "checklist.incident.date",
          "checkColumn": "checklist.corrective",
          "checkOperator": "contains",
          "checkValueType": "text",
          "checkText": "\"Final\", \"Verbal\", \"Written\"",
          "filters": [],
          "minimumEnabled": false,
          "minimum": 0,
          "points": 1,
          "autofailThreshold": 1,
          "autofailOperator": "greaterEqual",
          "rowPullConditions": [
            {
              "id": "mmqzoc0s55t47ex",
              "connector": "base",
              "column": "checklist.corrective",
              "dateColumn": "",
              "operator": "contains",
              "phrasesText": "\"Final\", \"Verbal\", \"Written\""
            },
            {
              "id": "mmqzodbze1175p0",
              "connector": "and",
              "column": "checklist.action.taken",
              "dateColumn": "Date",
              "operator": "contains",
              "phrasesText": "\"Addressed\""
            }
          ],
          "qaColumns": {},
          "withinUseRange": false,
          "withinDays": "",
          "withinRangeMin": "",
          "withinRangeMax": "",
          "withinCompareColumn": "",
          "trueValueEnabled": false,
          "trueValueSource": "",
          "trueValueColumn": "",
          "lookupMatchColumn": "",
          "lookupReturnColumn": "",
          "lookupDateColumn": ""
        },
        {
          "id": "mmr9otl9qp47fiu",
          "name": "Comp Calls",
          "source": "date",
          "calcType": "single",
          "audience": "rep",
          "scoreType": "points",
          "direction": "higher",
          "weight": "1",
          "format": "number",
          "missingRank": 999,
          "missingPoints": 0,
          "zeroCanWin": true,
          "minimumMonitors": 0,
          "column": "comp.calls.csr.ssr.name.this.is.the.person.being.complimented",
          "aggregate": "count",
          "withinCompareColumn": "",
          "withinUseRange": false,
          "withinDays": "",
          "withinRangeMin": "",
          "withinRangeMax": "",
          "leftSource": "date",
          "leftColumn": "",
          "operator": "divide",
          "rightSource": "date",
          "rightColumn": "",
          "customSource": "date",
          "expression": "",
          "checkDateColumn": "Date of Call",
          "checkColumn": "CSR/SSR Name (This is the person being complimented)",
          "checkOperator": "contains",
          "checkValueType": "text",
          "checkText": "",
          "filters": [],
          "minimumEnabled": false,
          "minimum": 0,
          "points": -3,
          "autofailThreshold": 1,
          "autofailOperator": "greaterEqual",
          "rowPullConditions": [
            {
              "id": "mmr9otl9vpelqou",
              "connector": "base",
              "column": "CSR/SSR Name (This is the person being complimented)",
              "dateColumn": "",
              "operator": "contains",
              "phrasesText": ""
            }
          ],
          "qaColumns": {},
          "trueValueEnabled": false,
          "trueValueSource": "",
          "trueValueColumn": "",
          "lookupMatchColumn": "",
          "lookupReturnColumn": "",
          "lookupDateColumn": ""
        },
        {
          "id": "mmrntovljm2izkz",
          "name": "DOH",
          "source": "retail_sv2",
          "calcType": "displayColumn",
          "audience": "rep",
          "scoreType": "display",
          "direction": "higher",
          "weight": "1",
          "format": "number",
          "missingRank": 999,
          "missingPoints": 0,
          "zeroCanWin": false,
          "minimumMonitors": 0,
          "column": "Agent_HireDate",
          "aggregate": "sum",
          "withinCompareColumn": "",
          "withinUseRange": false,
          "withinDays": "",
          "withinRangeMin": "",
          "withinRangeMax": "",
          "leftSource": "retail_sv2",
          "leftColumn": "",
          "operator": "divide",
          "rightSource": "retail_sv2",
          "rightColumn": "",
          "customSource": "retail_sv2",
          "expression": "",
          "checkDateColumn": "",
          "checkColumn": "",
          "checkOperator": "contains",
          "checkValueType": "text",
          "checkText": "",
          "filters": [],
          "minimumEnabled": false,
          "minimum": 0,
          "points": 1,
          "autofailThreshold": 1,
          "autofailOperator": "greaterEqual",
          "trueValueEnabled": false,
          "trueValueSource": "",
          "trueValueColumn": "",
          "rowPullConditions": [
            {
              "id": "mmrntovlvrsxzbt",
              "connector": "base",
              "column": "",
              "dateColumn": "",
              "operator": "contains",
              "phrasesText": ""
            }
          ],
          "qaColumns": {},
          "lookupVersion": 1,
          "displayMode": "lookup",
          "lookupMatchEntity": "representative",
          "lookupMatchColumn": "",
          "lookupReturnColumn": "Agent_HireDate",
          "lookupDateColumn": "",
          "lookupCustomValue": "",
          "lookupSelection": "latest",
          "displayCalculation": "raw",
          "displayValueType": "auto",
          "displayMissingMode": "blank",
          "displayMissingText": "",
          "displayRules": []
        }
      ],
      "sourceSettings": {
        "retail_sv2": {
          "headerRow": 4,
          "startCol": 3,
          "columns": {
            "team": "",
            "date": "Agent_HireDate",
            "useDateColumn": true,
            "skipTeamBuild": false,
            "nameMode": "firstLast",
            "fullName": "",
            "firstName": "Agent_Firstname",
            "lastName": "Agent_Surname",
            "convertLastFirst": false
          },
          "sheetName": "sv2",
          "manualHeaders": []
        },
        "retail_wiper": {
          "headerRow": 1,
          "startCol": 1,
          "columns": {
            "team": "",
            "date": "",
            "useDateColumn": null,
            "skipTeamBuild": false,
            "nameMode": "auto",
            "fullName": "",
            "firstName": "",
            "lastName": "",
            "convertLastFirst": false
          }
        },
        "referral_sv2": {
          "headerRow": 1,
          "startCol": 1,
          "columns": {
            "team": "",
            "date": "",
            "useDateColumn": false,
            "skipTeamBuild": true,
            "nameMode": "firstLast",
            "fullName": "",
            "firstName": "Agent_Firstname",
            "lastName": "Agent_Surname",
            "convertLastFirst": false
          },
          "sheetName": "sv2",
          "manualHeaders": []
        },
        "referral_wiper": {
          "headerRow": 1,
          "startCol": 1,
          "columns": {
            "team": "Team_Name",
            "date": "",
            "useDateColumn": false,
            "skipTeamBuild": false,
            "nameMode": "firstLast",
            "fullName": "",
            "firstName": "FIRST_NAME",
            "lastName": "LAST_NAME",
            "convertLastFirst": false
          },
          "sheetName": "sv2 wipers",
          "manualHeaders": []
        },
        "qa": {
          "headerRow": 1,
          "startCol": 1,
          "sheetName": "",
          "manualHeaders": [],
          "columns": {
            "agent": "Agent Name",
            "team": "Team",
            "score": "Score %",
            "interactionDate": "Interaction Start Time",
            "assignedDate": "Assigned Date",
            "date": "Interaction Start Time",
            "useDateColumn": true,
            "skipTeamBuild": false,
            "nameMode": "full",
            "fullName": "Agent Name",
            "firstName": "",
            "lastName": "",
            "convertLastFirst": false
          }
        },
        "checklist": {
          "headerRow": 1,
          "startCol": 1,
          "sheetName": "All Items",
          "manualHeaders": [],
          "columns": {
            "rep": "Associate Name",
            "team": "Coach Assigned",
            "date": "",
            "useDateColumn": null,
            "skipTeamBuild": false,
            "nameMode": "full",
            "fullName": "Associate Name",
            "firstName": "",
            "lastName": "",
            "convertLastFirst": false
          }
        },
        "documented_coaching": {
          "headerRow": 1,
          "startCol": 1,
          "sheetName": "",
          "manualHeaders": [],
          "columns": {
            "rep": "Associate name",
            "team": "Job Coach",
            "date": "",
            "useDateColumn": null,
            "skipTeamBuild": false,
            "nameMode": "full",
            "fullName": "Associate name",
            "firstName": "",
            "lastName": "",
            "convertLastFirst": false
          }
        },
        "comp_calls": {
          "headerRow": 1,
          "startCol": 1,
          "sheetName": "",
          "manualHeaders": [],
          "columns": {
            "rep": "CSR/SSR Name (This is the person being complimented)",
            "team": "CSR Team/Coach",
            "date": "Date of Call",
            "useDateColumn": true,
            "skipTeamBuild": false,
            "text": "Compliment",
            "nameMode": "full",
            "fullName": "CSR/SSR Name (This is the person being complimented)",
            "firstName": "",
            "lastName": "",
            "convertLastFirst": false
          }
        }
      }
    },
    {
      "id": "mmr9k7sqxghuah0",
      "name": "Referral",
      "type": "both",
      "tiebreaker": "overallScore",
      "criteria": [
        {
          "id": "mmr9k7yrhgo1ggz",
          "name": "Wipers",
          "source": "nondate",
          "calcType": "custom",
          "audience": "both",
          "scoreType": "rank",
          "direction": "higher",
          "weight": "1",
          "format": "number",
          "missingRank": 999,
          "missingPoints": 0,
          "zeroCanWin": false,
          "minimumMonitors": 0,
          "column": "",
          "aggregate": "sum",
          "withinCompareColumn": "",
          "withinUseRange": false,
          "withinDays": "",
          "withinRangeMin": "",
          "withinRangeMax": "",
          "leftSource": "nondate",
          "leftColumn": "",
          "operator": "divide",
          "rightSource": "nondate",
          "rightColumn": "",
          "customSource": "nondate",
          "expression": "[referral.wipers.accepted]/([referral.wipers.accepted]+[referral.wipers.declined])",
          "checkDateColumn": "",
          "checkColumn": "",
          "checkOperator": "contains",
          "checkValueType": "text",
          "checkText": "",
          "filters": [
            {
              "id": "mmr9k9gnhb959ss",
              "action": "include",
              "mode": "include",
              "operator": "greaterThan",
              "source": "nondate",
              "column": "referral.wipers.accepted",
              "values": [],
              "value": "5",
              "value2": "",
              "targetSource": "qa",
              "targetDateColumn": "",
              "targetValueColumn": "",
              "targetOp": "contains",
              "targetValue": "",
              "windowMode": "days",
              "dayWindow": "0",
              "dynamicColumn": true,
              "columnExpression": "[referral.wipers.accepted]+[referral.wipers.declined]",
              "dynamic": false,
              "expression": "",
              "rangeStart": "",
              "rangeEnd": ""
            }
          ],
          "minimumEnabled": false,
          "minimum": 0,
          "points": 1,
          "autofailThreshold": 1,
          "autofailOperator": "greaterEqual",
          "rowPullConditions": [
            {
              "id": "mmr9k7yrpr2ld1e",
              "connector": "base",
              "column": "",
              "dateColumn": "",
              "operator": "contains",
              "phrasesText": ""
            }
          ],
          "qaColumns": {},
          "trueValueEnabled": true,
          "trueValueSource": "referral_team_totals",
          "trueValueColumn": "Wiper Rate",
          "lookupMatchColumn": "",
          "lookupReturnColumn": "",
          "lookupDateColumn": ""
        },
        {
          "id": "mmr9k9651rb7oap",
          "name": "Call Quality",
          "source": "date",
          "calcType": "qaScore",
          "audience": "both",
          "scoreType": "rank",
          "direction": "higher",
          "weight": "1",
          "format": "number",
          "missingRank": 999,
          "missingPoints": 0,
          "zeroCanWin": false,
          "minimumMonitors": 0,
          "column": "",
          "aggregate": "sum",
          "withinCompareColumn": "",
          "withinUseRange": false,
          "withinDays": "",
          "withinRangeMin": "",
          "withinRangeMax": "",
          "leftSource": "date",
          "leftColumn": "",
          "operator": "divide",
          "rightSource": "date",
          "rightColumn": "",
          "customSource": "date",
          "expression": "",
          "checkDateColumn": "",
          "checkColumn": "",
          "checkOperator": "contains",
          "checkValueType": "text",
          "checkText": "",
          "filters": [],
          "minimumEnabled": false,
          "minimum": 0,
          "points": 1,
          "autofailThreshold": 1,
          "autofailOperator": "greaterEqual",
          "rowPullConditions": [
            {
              "id": "mmr9k9655zyu1al",
              "connector": "base",
              "column": "",
              "dateColumn": "",
              "operator": "contains",
              "phrasesText": ""
            }
          ],
          "qaColumns": {
            "rep": "Representative",
            "team": "Coach",
            "score": "qa.genesys.evaluation.score.score.percent",
            "date": "qa.genesys.evaluation.score.assigned.date"
          },
          "trueValueEnabled": false,
          "trueValueSource": "",
          "trueValueColumn": "",
          "lookupMatchColumn": "",
          "lookupReturnColumn": "",
          "lookupDateColumn": ""
        },
        {
          "id": "mmrfb7f5hs3iaob",
          "name": "ITAC",
          "source": "nondate",
          "calcType": "multi",
          "audience": "team",
          "scoreType": "rank",
          "direction": "higher",
          "weight": "1",
          "format": "number",
          "missingRank": 999,
          "missingPoints": 0,
          "zeroCanWin": false,
          "minimumMonitors": 0,
          "column": "",
          "aggregate": "sum",
          "withinCompareColumn": "",
          "withinUseRange": false,
          "withinDays": "",
          "withinRangeMin": "",
          "withinRangeMax": "",
          "leftSource": "nondate",
          "leftColumn": "referral.sv2.accepted.itac",
          "operator": "divide",
          "rightSource": "nondate",
          "rightColumn": "referral.sv2.offered.itac",
          "customSource": "nondate",
          "expression": "",
          "checkDateColumn": "",
          "checkColumn": "",
          "checkOperator": "contains",
          "checkValueType": "text",
          "checkText": "",
          "filters": [
            {
              "id": "mmrfbadfrxkxp6z",
              "action": "include",
              "mode": "include",
              "operator": "greaterThan",
              "source": "nondate",
              "column": "referral.sv2.offered.itac",
              "values": [],
              "value": "3",
              "value2": "",
              "targetSource": "qa",
              "targetDateColumn": "",
              "targetValueColumn": "",
              "targetOp": "contains",
              "targetValue": "",
              "windowMode": "days",
              "dayWindow": "0",
              "dynamic": false,
              "expression": "",
              "dynamicColumn": false,
              "columnExpression": "",
              "rangeStart": "",
              "rangeEnd": ""
            }
          ],
          "minimumEnabled": false,
          "minimum": 0,
          "points": 1,
          "autofailThreshold": 1,
          "autofailOperator": "greaterEqual",
          "rowPullConditions": [
            {
              "id": "mmrfb7f5nn5lw2k",
              "connector": "base",
              "column": "",
              "dateColumn": "",
              "operator": "contains",
              "phrasesText": ""
            }
          ],
          "qaColumns": {},
          "trueValueEnabled": true,
          "trueValueSource": "referral_team_totals",
          "trueValueColumn": "ITAC %",
          "lookupMatchColumn": "",
          "lookupReturnColumn": "",
          "lookupDateColumn": ""
        },
        {
          "id": "mmrfb8hbwg2dl6m",
          "name": "Comp Calls",
          "source": "date",
          "calcType": "single",
          "audience": "rep",
          "scoreType": "points",
          "direction": "higher",
          "weight": "1",
          "format": "number",
          "missingRank": 999,
          "missingPoints": 0,
          "zeroCanWin": true,
          "minimumMonitors": 0,
          "column": "comp.calls.taken.by.this.is.the.person.reporting.the.compliment",
          "aggregate": "count",
          "withinCompareColumn": "",
          "withinUseRange": false,
          "withinDays": "",
          "withinRangeMin": "",
          "withinRangeMax": "",
          "leftSource": "date",
          "leftColumn": "",
          "operator": "divide",
          "rightSource": "date",
          "rightColumn": "",
          "customSource": "date",
          "expression": "",
          "checkDateColumn": "comp.calls.date.of.call",
          "checkColumn": "comp.calls.csr.ssr.name.this.is.the.person.being.complimented",
          "checkOperator": "contains",
          "checkValueType": "text",
          "checkText": "",
          "filters": [],
          "minimumEnabled": false,
          "minimum": 0,
          "points": -3,
          "autofailThreshold": 1,
          "autofailOperator": "greaterEqual",
          "rowPullConditions": [
            {
              "id": "mmrfb8hc6m3o72d",
              "connector": "base",
              "column": "comp.calls.csr.ssr.name.this.is.the.person.being.complimented",
              "dateColumn": "",
              "operator": "contains",
              "phrasesText": ""
            }
          ],
          "qaColumns": {},
          "trueValueEnabled": false,
          "trueValueSource": "",
          "trueValueColumn": "",
          "lookupMatchColumn": "",
          "lookupReturnColumn": "",
          "lookupDateColumn": ""
        },
        {
          "id": "mmrfcw85jb88zvb",
          "name": "Checklist Item",
          "source": "date",
          "calcType": "checklistCount",
          "audience": "rep",
          "scoreType": "rank",
          "direction": "higher",
          "weight": "autofail",
          "format": "number",
          "missingRank": 999,
          "missingPoints": 0,
          "zeroCanWin": false,
          "minimumMonitors": 0,
          "column": "",
          "aggregate": "sum",
          "withinCompareColumn": "",
          "withinUseRange": false,
          "withinDays": "",
          "withinRangeMin": "",
          "withinRangeMax": "",
          "leftSource": "date",
          "leftColumn": "",
          "operator": "divide",
          "rightSource": "date",
          "rightColumn": "",
          "customSource": "date",
          "expression": "",
          "checkDateColumn": "checklist.incident.date",
          "checkColumn": "checklist.corrective",
          "checkOperator": "contains",
          "checkValueType": "text",
          "checkText": "\"final\"",
          "filters": [],
          "minimumEnabled": false,
          "minimum": 0,
          "points": 1,
          "autofailThreshold": 1,
          "autofailOperator": "greaterEqual",
          "rowPullConditions": [
            {
              "id": "mmrfcw85pwegns0",
              "connector": "base",
              "column": "checklist.corrective",
              "dateColumn": "",
              "operator": "contains",
              "phrasesText": "\"final\""
            },
            {
              "id": "mmrfcy1h5h07pbx",
              "connector": "and",
              "column": "checklist.action.taken",
              "dateColumn": "checklist.incident.date",
              "operator": "contains",
              "phrasesText": "\"Addressed\""
            }
          ],
          "qaColumns": {},
          "trueValueEnabled": false,
          "trueValueSource": "",
          "trueValueColumn": "",
          "lookupMatchColumn": "",
          "lookupReturnColumn": "",
          "lookupDateColumn": ""
        }
      ],
      "sourceSettings": {
        "retail_sv2": {
          "headerRow": 4,
          "startCol": 3,
          "columns": {
            "team": "",
            "date": "Agent_HireDate",
            "useDateColumn": true,
            "skipTeamBuild": false,
            "nameMode": "firstLast",
            "fullName": "",
            "firstName": "Agent_Firstname",
            "lastName": "Agent_Surname",
            "convertLastFirst": false
          },
          "sheetName": "sv2",
          "manualHeaders": []
        },
        "retail_wiper": {
          "headerRow": 1,
          "startCol": 1,
          "columns": {
            "team": "",
            "date": "",
            "useDateColumn": null,
            "skipTeamBuild": false,
            "nameMode": "auto",
            "fullName": "",
            "firstName": "",
            "lastName": "",
            "convertLastFirst": false
          }
        },
        "referral_sv2": {
          "headerRow": 1,
          "startCol": 1,
          "columns": {
            "team": "",
            "date": "",
            "useDateColumn": false,
            "skipTeamBuild": true,
            "nameMode": "firstLast",
            "fullName": "",
            "firstName": "Agent_Firstname",
            "lastName": "Agent_Surname",
            "convertLastFirst": false
          },
          "sheetName": "sv2",
          "manualHeaders": []
        },
        "referral_wiper": {
          "headerRow": 1,
          "startCol": 1,
          "columns": {
            "team": "Team_Name",
            "date": "",
            "useDateColumn": false,
            "skipTeamBuild": false,
            "nameMode": "firstLast",
            "fullName": "",
            "firstName": "FIRST_NAME",
            "lastName": "LAST_NAME",
            "convertLastFirst": false
          },
          "sheetName": "sv2 wipers",
          "manualHeaders": []
        },
        "qa": {
          "headerRow": 1,
          "startCol": 1,
          "sheetName": "",
          "manualHeaders": [],
          "columns": {
            "agent": "Agent Name",
            "team": "Team",
            "score": "Score %",
            "interactionDate": "Interaction Start Time",
            "assignedDate": "Assigned Date",
            "date": "Interaction Start Time",
            "useDateColumn": true,
            "skipTeamBuild": false,
            "nameMode": "full",
            "fullName": "Agent Name",
            "firstName": "",
            "lastName": "",
            "convertLastFirst": false
          }
        },
        "checklist": {
          "headerRow": 1,
          "startCol": 1,
          "sheetName": "All Items",
          "manualHeaders": [],
          "columns": {
            "rep": "Associate Name",
            "team": "Coach Assigned",
            "date": "",
            "useDateColumn": null,
            "skipTeamBuild": false,
            "nameMode": "full",
            "fullName": "Associate Name",
            "firstName": "",
            "lastName": "",
            "convertLastFirst": false
          }
        },
        "documented_coaching": {
          "headerRow": 1,
          "startCol": 1,
          "sheetName": "",
          "manualHeaders": [],
          "columns": {
            "rep": "Associate name",
            "team": "Job Coach",
            "date": "",
            "useDateColumn": null,
            "skipTeamBuild": false,
            "nameMode": "full",
            "fullName": "Associate name",
            "firstName": "",
            "lastName": "",
            "convertLastFirst": false
          }
        },
        "comp_calls": {
          "headerRow": 1,
          "startCol": 1,
          "sheetName": "",
          "manualHeaders": [],
          "columns": {
            "rep": "CSR/SSR Name (This is the person being complimented)",
            "team": "CSR Team/Coach",
            "date": "Date of Call",
            "useDateColumn": true,
            "skipTeamBuild": false,
            "text": "Compliment",
            "nameMode": "full",
            "fullName": "CSR/SSR Name (This is the person being complimented)",
            "firstName": "",
            "lastName": "",
            "convertLastFirst": false
          }
        }
      }
    },
    {
      "id": "mmrnr5a4qnivd5d",
      "name": "Coaching Types",
      "type": "both",
      "tiebreaker": "overallScore",
      "criteria": [
        {
          "id": "mmrnr5dyv1flv1i",
          "name": "Save the Sale Coaching",
          "source": "date",
          "calcType": "checklistCount",
          "audience": "both",
          "scoreType": "points",
          "direction": "higher",
          "weight": "1",
          "format": "number",
          "missingRank": 999,
          "missingPoints": 0,
          "zeroCanWin": false,
          "minimumMonitors": 0,
          "column": "",
          "aggregate": "sum",
          "withinCompareColumn": "",
          "withinUseRange": false,
          "withinDays": "",
          "withinRangeMin": "",
          "withinRangeMax": "",
          "leftSource": "date",
          "leftColumn": "",
          "operator": "divide",
          "rightSource": "date",
          "rightColumn": "",
          "customSource": "date",
          "expression": "",
          "checkDateColumn": "documented.coaching.coaching.date",
          "checkColumn": "documented.coaching.description",
          "checkOperator": "contains",
          "checkValueType": "text",
          "checkText": "\"save the sale\", \"sts\", \"objection handling\", \"saving the sale\"",
          "filters": [],
          "minimumEnabled": false,
          "minimum": 0,
          "points": -1,
          "autofailThreshold": 1,
          "autofailOperator": "greaterEqual",
          "trueValueEnabled": false,
          "trueValueSource": "",
          "trueValueColumn": "",
          "rowPullConditions": [
            {
              "id": "mmrnr5dyy48helr",
              "connector": "base",
              "column": "documented.coaching.description",
              "dateColumn": "",
              "operator": "contains",
              "phrasesText": "\"save the sale\", \"sts\", \"objection handling\", \"saving the sale\""
            },
            {
              "id": "mmsnj92qu4m40ya",
              "connector": "and",
              "column": "",
              "dateColumn": "documented.coaching.coaching.date",
              "operator": "notContains",
              "phrasesText": "\"team huddle\""
            }
          ],
          "qaColumns": {},
          "lookupMatchColumn": "",
          "lookupReturnColumn": "",
          "lookupDateColumn": ""
        },
        {
          "id": "mmrnrcs7vugnewr",
          "name": "Save the Sale Corrective",
          "source": "date",
          "calcType": "checklistCount",
          "audience": "both",
          "scoreType": "points",
          "direction": "higher",
          "weight": "1",
          "format": "number",
          "missingRank": 999,
          "missingPoints": 0,
          "zeroCanWin": true,
          "minimumMonitors": 0,
          "column": "checklist.incident.date",
          "aggregate": "sum",
          "withinCompareColumn": "",
          "withinUseRange": false,
          "withinDays": "",
          "withinRangeMin": "",
          "withinRangeMax": "",
          "leftSource": "date",
          "leftColumn": "",
          "operator": "divide",
          "rightSource": "date",
          "rightColumn": "",
          "customSource": "date",
          "expression": "",
          "checkDateColumn": "checklist.incident.date",
          "checkColumn": "checklist.corrective",
          "checkOperator": "contains",
          "checkValueType": "text",
          "checkText": "\"final\", \"written\", \"verbal\"",
          "filters": [],
          "minimumEnabled": false,
          "minimum": 0,
          "points": -1,
          "autofailThreshold": 1,
          "autofailOperator": "greaterEqual",
          "trueValueEnabled": false,
          "trueValueSource": "",
          "trueValueColumn": "",
          "rowPullConditions": [
            {
              "id": "mmrnrcs80g1vsaq",
              "connector": "base",
              "column": "checklist.corrective",
              "dateColumn": "",
              "operator": "contains",
              "phrasesText": "\"final\", \"written\", \"verbal\""
            },
            {
              "id": "mmrnrdses32b5qt",
              "connector": "and",
              "column": "checklist.action.taken",
              "dateColumn": "checklist.incident.date",
              "operator": "contains",
              "phrasesText": "\"addressed\""
            },
            {
              "id": "mmrnre1w6ubk31l",
              "connector": "and",
              "column": "checklist.incident",
              "dateColumn": "checklist.incident.date",
              "operator": "contains",
              "phrasesText": "\"Appointment\""
            }
          ],
          "qaColumns": {},
          "lookupMatchColumn": "",
          "lookupReturnColumn": "",
          "lookupDateColumn": ""
        },
        {
          "id": "mmrnrsi87q3fv75",
          "name": "Call Quality",
          "source": "date",
          "calcType": "checklistCount",
          "audience": "both",
          "scoreType": "points",
          "direction": "higher",
          "weight": "1",
          "format": "number",
          "missingRank": 999,
          "missingPoints": 0,
          "zeroCanWin": false,
          "minimumMonitors": 0,
          "column": "",
          "aggregate": "sum",
          "withinCompareColumn": "",
          "withinUseRange": false,
          "withinDays": "",
          "withinRangeMin": "",
          "withinRangeMax": "",
          "leftSource": "date",
          "leftColumn": "",
          "operator": "divide",
          "rightSource": "date",
          "rightColumn": "",
          "customSource": "date",
          "expression": "",
          "checkDateColumn": "documented.coaching.coaching.date",
          "checkColumn": "documented.coaching.description",
          "checkOperator": "contains",
          "checkValueType": "text",
          "checkText": "\"Call Quality\", \"CQ\", \"Compliance Score\", \"qualtrics\", \"Monitor\"",
          "filters": [],
          "minimumEnabled": false,
          "minimum": 0,
          "points": -1,
          "autofailThreshold": 1,
          "autofailOperator": "greaterEqual",
          "trueValueEnabled": false,
          "trueValueSource": "",
          "trueValueColumn": "",
          "rowPullConditions": [
            {
              "id": "mmrnr5dyy48helr",
              "connector": "base",
              "column": "documented.coaching.description",
              "dateColumn": "",
              "operator": "contains",
              "phrasesText": "\"Call Quality\", \"CQ\", \"Compliance Score\", \"qualtrics\", \"Monitor\""
            }
          ],
          "qaColumns": {},
          "lookupMatchColumn": "",
          "lookupReturnColumn": "",
          "lookupDateColumn": ""
        },
        {
          "id": "mmrnruvqtu6a63p",
          "name": "Date of Hire",
          "source": "nondate",
          "calcType": "displayColumn",
          "audience": "rep",
          "scoreType": "display",
          "direction": "higher",
          "weight": "1",
          "format": "number",
          "missingRank": 999,
          "missingPoints": 0,
          "zeroCanWin": true,
          "minimumMonitors": 0,
          "column": "Agent_HireDate",
          "aggregate": "avg",
          "withinCompareColumn": "",
          "withinUseRange": false,
          "withinDays": "",
          "withinRangeMin": "",
          "withinRangeMax": "",
          "leftSource": "nondate",
          "leftColumn": "",
          "operator": "divide",
          "rightSource": "nondate",
          "rightColumn": "",
          "customSource": "nondate",
          "expression": "",
          "checkDateColumn": "",
          "checkColumn": "",
          "checkOperator": "contains",
          "checkValueType": "text",
          "checkText": "",
          "filters": [],
          "minimumEnabled": false,
          "minimum": 0,
          "points": 1,
          "autofailThreshold": 1,
          "autofailOperator": "greaterEqual",
          "trueValueEnabled": false,
          "trueValueSource": "",
          "trueValueColumn": "",
          "rowPullConditions": [
            {
              "id": "mmrnruvqwm78ver",
              "connector": "base",
              "column": "",
              "dateColumn": "",
              "operator": "contains",
              "phrasesText": ""
            }
          ],
          "qaColumns": {},
          "lookupVersion": 2,
          "displayMode": "lookup",
          "lookupMatchEntity": "representative",
          "lookupMatchColumn": "Representative",
          "lookupReturnColumn": "Agent_HireDate",
          "lookupDateColumn": "",
          "lookupCustomValue": "",
          "lookupSelection": "latest",
          "displayCalculation": "raw",
          "displayValueType": "auto",
          "displayMissingMode": "blank",
          "displayMissingText": "",
          "displayRules": []
        },
        {
          "id": "mmrnwrdu29u5fo7",
          "name": "Cash Appointment Rate",
          "source": "retail_team_totals",
          "calcType": "displayColumn",
          "audience": "team",
          "scoreType": "display",
          "direction": "higher",
          "weight": "1",
          "format": "number",
          "missingRank": 999,
          "missingPoints": 0,
          "zeroCanWin": false,
          "minimumMonitors": 0,
          "column": "Consumer Appointment Rate",
          "aggregate": "sum",
          "withinCompareColumn": "",
          "withinUseRange": false,
          "withinDays": "",
          "withinRangeMin": "",
          "withinRangeMax": "",
          "leftSource": "retail_team_totals",
          "leftColumn": "",
          "operator": "divide",
          "rightSource": "retail_team_totals",
          "rightColumn": "",
          "customSource": "retail_team_totals",
          "expression": "",
          "checkDateColumn": "",
          "checkColumn": "",
          "checkOperator": "contains",
          "checkValueType": "text",
          "checkText": "",
          "filters": [],
          "minimumEnabled": false,
          "minimum": 0,
          "points": 1,
          "autofailThreshold": 1,
          "autofailOperator": "greaterEqual",
          "trueValueEnabled": false,
          "trueValueSource": "",
          "trueValueColumn": "",
          "rowPullConditions": [
            {
              "id": "mmrnwrdubcbc2h1",
              "connector": "base",
              "column": "",
              "dateColumn": "",
              "operator": "contains",
              "phrasesText": ""
            }
          ],
          "qaColumns": {},
          "lookupVersion": 2,
          "displayMode": "lookup",
          "lookupMatchEntity": "team",
          "lookupMatchColumn": "Name",
          "lookupReturnColumn": "Consumer Appointment Rate",
          "lookupDateColumn": "",
          "lookupCustomValue": "",
          "lookupSelection": "latest",
          "displayCalculation": "raw",
          "displayValueType": "auto",
          "displayMissingMode": "blank",
          "displayMissingText": "",
          "displayRules": []
        }
      ],
      "sourceSettings": {
        "retail_sv2": {
          "headerRow": 4,
          "startCol": 3,
          "columns": {
            "team": "",
            "date": "",
            "useDateColumn": null,
            "skipTeamBuild": false,
            "nameMode": "auto",
            "fullName": "",
            "firstName": "",
            "lastName": "",
            "convertLastFirst": false
          }
        },
        "retail_wiper": {
          "headerRow": 1,
          "startCol": 1,
          "columns": {
            "team": "",
            "date": "",
            "useDateColumn": null,
            "skipTeamBuild": false,
            "nameMode": "auto",
            "fullName": "",
            "firstName": "",
            "lastName": "",
            "convertLastFirst": false
          }
        },
        "referral_sv2": {
          "headerRow": 1,
          "startCol": 3,
          "columns": {
            "team": "",
            "date": "",
            "useDateColumn": null,
            "skipTeamBuild": true,
            "nameMode": "auto",
            "fullName": "",
            "firstName": "",
            "lastName": "",
            "convertLastFirst": false
          }
        },
        "referral_wiper": {
          "headerRow": 1,
          "startCol": 1,
          "columns": {
            "team": "",
            "date": "",
            "useDateColumn": null,
            "skipTeamBuild": false,
            "nameMode": "auto",
            "fullName": "",
            "firstName": "",
            "lastName": "",
            "convertLastFirst": false
          }
        },
        "qa": {
          "headerRow": 1,
          "startCol": 1,
          "sheetName": "",
          "manualHeaders": [],
          "columns": {
            "agent": "Agent Name",
            "team": "Team",
            "score": "Score %",
            "interactionDate": "Interaction Start Time",
            "assignedDate": "Assigned Date",
            "date": "Interaction Start Time",
            "useDateColumn": true,
            "skipTeamBuild": false,
            "nameMode": "full",
            "fullName": "Agent Name",
            "firstName": "",
            "lastName": "",
            "convertLastFirst": false
          }
        },
        "checklist": {
          "headerRow": 1,
          "startCol": 1,
          "sheetName": "All Items",
          "manualHeaders": [],
          "columns": {
            "rep": "Associate Name",
            "team": "Coach Assigned",
            "date": "",
            "useDateColumn": null,
            "skipTeamBuild": false,
            "nameMode": "full",
            "fullName": "Associate Name",
            "firstName": "",
            "lastName": "",
            "convertLastFirst": false
          }
        },
        "documented_coaching": {
          "headerRow": 1,
          "startCol": 1,
          "sheetName": "",
          "manualHeaders": [],
          "columns": {
            "rep": "Associate name",
            "team": "Job Coach",
            "date": "",
            "useDateColumn": null,
            "skipTeamBuild": false,
            "nameMode": "full",
            "fullName": "Associate name",
            "firstName": "",
            "lastName": "",
            "convertLastFirst": false
          }
        },
        "comp_calls": {
          "headerRow": 1,
          "startCol": 1,
          "sheetName": "",
          "manualHeaders": [],
          "columns": {
            "rep": "CSR/SSR Name (This is the person being complimented)",
            "team": "CSR Team/Coach",
            "date": "Date of Call",
            "useDateColumn": true,
            "skipTeamBuild": false,
            "text": "Compliment",
            "nameMode": "full",
            "fullName": "CSR/SSR Name (This is the person being complimented)",
            "firstName": "",
            "lastName": "",
            "convertLastFirst": false
          }
        }
      }
    }
  ],
  "customSources": []
};
const allstarModelSchemaVersion = 4;
const allstarDataSchemaVersion = 1;
const allstarSourceMappingVersion = 1;
