'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const M=require('../../../shared/coachtools-monthly.js'),C=require('../js/metric-components.js'),fixture=require('./fixtures/monthly-hierarchy.js');
const op=M.source(fixture.opportunity,'op.csv'),w=M.source(fixture.wiper,'w.csv');
const bundle=()=>M.add(M.add(M.create('mixed'),op).bundle,w).bundle;
const plain=x=>JSON.parse(JSON.stringify(x));
const approx=(a,b)=>assert.ok(Math.abs(a-b)<1e-8,`${a} != ${b}`);
function harness(){
 const {parseHTML}=require('linkedom'),{IDBFactory}=require('fake-indexeddb'),root=path.resolve(__dirname,'..');
 const html=fs.readFileSync(path.join(root,'allstar.html'),'utf8'),{document}=parseHTML(html),db=new IDBFactory(),storage=new Map(),errors=[];
 const proto=Object.getPrototypeOf(document.createElement('select')),get=Object.getOwnPropertyDescriptor(proto,'value').get;
 Object.defineProperty(proto,'value',{configurable:true,get,set(v){for(const o of this.querySelectorAll('option'))o.removeAttribute('selected');this.querySelectorAll('option').forEach(o=>{if(o.value===v)o.setAttribute('selected','');});}});
 const window={document,indexedDB:db,addEventListener(){},location:{search:''}};
 const context=vm.createContext({document,window,indexedDB:db,localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v),removeItem:k=>storage.delete(k)},console:{info(){},warn(){},error(){}},performance,setTimeout,clearTimeout,setInterval,clearInterval,structuredClone,URL,TextEncoder,TextDecoder,requestAnimationFrame:fn=>setTimeout(fn,0),navigator:{},location:{search:''},alert:m=>errors.push(m),confirm:()=>true,XLSX:require('../../../vendor/xlsx.full.min.js')});
 const scripts=[...html.matchAll(/<script src="(js\/[^"]+)"><\/script>/g)].map(m=>m[1]).filter(n=>n!=='js/app.js');
 vm.runInContext(fs.readFileSync(path.join(root,'../../shared/coachtools-monthly.js'),'utf8')+'\n'+scripts.map(n=>fs.readFileSync(path.join(root,n),'utf8')).join('\n'),context);
 vm.runInContext('setStatus=renderEditModelSafe=renderTeamSelect=updateResearchCacheBadge=()=>{};showProgress=hideProgress=updateProgress=()=>{};state.startup.running=false;state.lifecycle.hidden=false;loadModels();',context);
 return {context,document,errors,run:s=>vm.runInContext(s,context),stop:()=>vm.runInContext('state.lifecycle.closing=true;clearTimeout(state.importCacheSaveTimer);',context)};
}
(async()=>{
 const b=bundle(),out=M.compile(b);
 assert.equal(out.canApply,true);assert.equal(op.mapping.manager,0);assert.equal(op.rows.filter(r=>r.kind==='detail').length,3);
 assert.equal(out.reps.some(r=>r.name==='Total'),false);assert.equal(out.overall.wiper.accepted,20);assert.equal(out.overall.wiper.offered,50);
 const a=out.teams.find(t=>t.coach==='Coach A'),manager=out.managers.find(m=>m.manager==='Manager A');
 assert.equal(a.segments.consumer.opportunities,15);assert.equal(a.calculatedSegments.consumer.opportunities,10);assert.equal(a.totalSource,'Exported total');assert.equal(a.area,'retail');
 assert.equal(out.teams.find(t=>t.coach==='Coach B').area,'referral');assert.equal(manager.segments.consumer.opportunities,30);assert.equal(manager.totalSource,'Exported total');
 assert.equal(a.wiper.accepted,11);assert.equal(out.teams.find(t=>t.coach==='Coach B').wiper.accepted,4);
 assert.equal(out.reps.find(r=>r.name==='Rep Two').wiper.status,'missing');assert.equal(out.reps.find(r=>r.name==='Unattributed Representative').ranked,false);
 assert.equal(out.managers.reduce((n,m)=>n+(m.wiper.accepted||0),0),20);assert.equal(out.managers.reduce((n,m)=>n+(m.wiper.offered||0),0),50);assert.equal(manager.wiper.missingRepresentatives,2);
 assert.equal(out.managers.find(m=>m.manager==='Unassigned Manager').wiper.accepted,5);
 assert.ok(out.issues.some(i=>i.code==='subtotal-reconciliation'));assert.equal(out.issues.some(i=>i.code==='wiper-reconciliation'),false);
 const filtered=M.compile(b,{manager:'Manager A',area:'retail'}).managers[0];assert.equal(filtered.segments.consumer.opportunities,15);assert.equal(filtered.totalSource,'Filtered total');
 const selected=M.compile(b,{selection:[['Rep One','Coach A']]}).teams[0];assert.equal(selected.segments.consumer.opportunities,5);assert.equal(selected.wiper.accepted,7);assert.equal(selected.totalSource,'Filtered total');
 const fullCoachSelection=out.reps.filter(r=>r.coach==='Coach A').map(r=>[r.name,r.coach]);assert.equal(M.compile(b,{selection:fullCoachSelection}).teams[0].totalSource,'Exported total');
 const calc=M.clone(b);calc.opportunity.rows=calc.opportunity.rows.filter(r=>r.kind!=='coach');assert.equal(M.compile(calc).teams[0].totalSource,'Calculated total');
 const conflict=M.clone(b);conflict.opportunity.rows.find(r=>r.name==='Rep Two').manager='Manager B';assert.ok(M.compile(conflict).issues.some(i=>i.code==='manager-conflict'));assert.equal(M.compile(conflict).teams[0].manager,'');
 const zero=M.clone(b);for(const s of M.SEGMENTS)zero.opportunity.rows.find(r=>r.kind==='coach').segments[s].opportunities=M.cell(0);assert.equal(M.compile(zero).teams[0].area,'unclassified');
 assert.equal(M.add(b,{...M.clone(w),name:'renamed.csv'}).duplicate,true);
 const overlap=M.source([fixture.wiper[0],['9/6/2026','Coach A','Rep One',2,10]],'subset.csv');assert.equal(M.compile(M.add(b,overlap).bundle).overall.wiper.accepted,20);
 const correction=M.source([fixture.wiper[0],['9/6/2026','Coach A','Rep One',9,10]],'corrected.csv');let replaced=M.add(b,correction).bundle;assert.equal(M.compile(replaced).canApply,false);replaced.wipers.at(-1).replaces=w.id;assert.equal(M.compile(replaced).overall.wiper.accepted,9);
 const changed=M.clone(fixture.opportunity);changed[6][4]=6;const correctedOp=M.add(b,M.source(changed,'corrected-op.csv')).bundle;assert.equal(correctedOp.wipers.length,1);
 const blankCoach=M.add(b,M.source([fixture.wiper[0],['9/20/2026','','Rep Two',1,2]],'blank-coach.csv')).bundle;assert.equal(M.compile(blankCoach).teams.find(t=>t.coach==='Unassigned Coach').wiper.accepted,1);
 const src=M.stats(out.reps.find(r=>r.name==='Rep One'&&r.hasOpportunity),true);assert.equal(src['Consumer SMS Rate'],60);assert.equal(src['Insurance SMS Rate'],80);
 const settings={componentFields:['A','B','C'],excludeMissing:true},r={Representative:'Rep A',Coach:'Coach A',A:'80%',B:0,C:60};
 approx(C.evaluate(settings,[r]).value,140/3);assert.equal(C.evaluate({...settings,excludeZero:true},[r]).value,70);
 assert.equal(C.evaluate(settings,[{...r,B:''}]).value,70);assert.equal(C.evaluate({...settings,excludeZero:true},[{...r,A:0,B:0,C:0}]).value,null);
 assert.equal(C.evaluate({...settings,excludeMissing:false},[{...r,B:''}]).value,null);
 approx(C.evaluate({...settings,excludeMissing:false,missingAsZero:true},[{...r,B:''}]).value,140/3);
 assert.equal(C.evaluate(settings,[{...r,B:'invalid'}]).value,70);assert.equal(C.evaluate(settings,[{...r,B:'*'}]).representatives[0].components[1].status,'suppressed');
 assert.equal(C.evaluate(settings,[{...r,A:.8,B:0,C:.6,_fieldMeta:{A:{storageUnit:'fraction'},C:{storageUnit:'fraction'}}}]).value,140/3);
 const reps=[r,r,{Representative:'Rep B',Coach:'Coach B',A:100,B:100,C:100},{Representative:'Rep C',Coach:'Coach B',A:100,B:100,C:100}];approx(C.evaluate(settings,reps).value,(140/3+200)/3);
 assert.equal(C.evaluate(settings,[r,{...r,Coach:'Other'}]).value,null,'ambiguous names must not be silently merged');
 const h=harness();try{
  h.context.bundle=b;assert.equal(await h.run('commitMonthlyBundle(bundle)'),true,h.errors.join('\n'));
  assert.equal(h.run('state.data.retail.controlRoster.some(r=>r._rep==="Unattributed Representative")'),false);
  assert.equal(h.run('state.data.retail.teamTotals.rows[0]["Consumer Opportunities"]'),15);
  assert.equal(h.run('getRowsRaw("monthly_wiper").reduce((n,r)=>n+(r.Accepted||0),0)'),20);
  assert.equal(h.run('getRowsRaw("monthly_opportunity").length'),3);
  assert.equal(h.run('buildCompactTeamIndexFromRows().reps.some(r=>r.name==="Unattributed Representative")'),false);
  h.run('const filteredOptions={};');assert.equal(h.run('trueTeamCriterionValue({source:"retail_sv2",trueValueSource:"retail_team_totals",trueValueColumn:"Consumer Opportunities",filters:[{column:"Representative",operator:"equals",value:"Rep One"}]},{kind:"team",name:"Coach A"},filteredOptions)'),5);
  assert.match(h.run('filteredOptions.trueValueDiagnostics[0].note'),/Filtered total/);
  assert.equal(h.run('getHeaders("monthly_opportunity").includes("Insurance SMS Rate")'),true);
  h.run("state.data.referral.itac=[{Accepted:1}];state.data.referral.headers.itac=['Accepted'];");assert.equal(await h.run('commitMonthlyBundle(bundle)'),true);assert.equal(h.run('state.data.referral.itac.length'),1);assert.match(h.run('state.data.referral.independentSourceStatus.itac'),/Preserved/);
  h.run("state.metrics=[normalizeMetric({id:'sms',name:'Average of Segment SMS Rates',source:'monthly_opportunity',mode:'component_avg',componentFields:['Commercial SMS Rate','Consumer SMS Rate','Insurance SMS Rate'],excludeZero:true,excludeMissing:true})];");
  approx(h.run('evaluateMetric(state.metrics[0],getRowsRaw("monthly_opportunity"),"monthly_opportunity")'),(70+70+20)/3);
  h.run('openMetricEditor("sms");');assert.equal(h.document.querySelectorAll('#metricComponents option:checked').length,3);
  assert.equal(h.run('metricFromEditor().excludeZero'),true);assert.equal(h.run('metricFromEditor().componentFields.length'),3);
  h.run('renderMetricFoundPreview();');assert.match(h.document.getElementById('metricFoundPreview').textContent,/70.00%/);
  assert.equal(await h.run('saveMetrics()'),true);h.run('state.metrics=[];');await h.run('loadMetrics()');assert.equal(h.run('state.metrics[0].excludeZero'),true);assert.equal(h.run('state.metrics[0].aggregationOrder'),'representative-first');
  h.run('openMonthlyManagerReport();');assert.match(h.document.getElementById('monthlyManagerReport').textContent,/Exported total/);assert.match(h.document.getElementById('monthlyManagerReport').textContent,/Unassigned Manager/);h.document.querySelector('[data-monthly-close]').click();
  h.context.filtered=[['Rep One','Coach A']];assert.equal(h.run('monthlyAreaData(bundle,"retail",{},filtered).teamTotals.rows[0]["Consumer Opportunities"]'),5);
  assert.equal(h.run('monthlyAreaData(bundle,"retail",{},filtered).teamTotals.rows[0]._totalSource'),'Filtered total');
  const before=h.run('JSON.stringify(state.data.retail)');h.context.invalid=replaced;h.context.invalid.wipers.at(-1).replaces='missing';assert.equal(await h.run('commitMonthlyBundle(invalid)'),false);assert.equal(h.run('JSON.stringify(state.data.retail)'),before);
 }finally{h.stop();}
 console.log('PASS hierarchical imports, exported totals, exact boundary, source-owned Wipers, manager reconciliation, overlaps, Metrics exclusions/units/representative weighting, editor, persistence and rollback');
})().catch(e=>{console.error(e);process.exitCode=1;});
