#!/usr/bin/env node
'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const workflow=require('../qualtrics/workflow.js');
const engine=require('../qualtrics/individual-messages.js');
const XLSX=require('../../../vendor/xlsx.full.min.js');
const html=fs.readFileSync(path.join(__dirname,'../qualtrics/generator.html'),'utf8');
const ui=fs.readFileSync(path.join(__dirname,'../qualtrics/individual-ui.js'),'utf8');
const rules=[{id:'a',title:'Insurance Cash',baseName:'Insurance Cash',ruleType:'multiHeader',individualMessage:{concern:{enabled:true,source:'cashAppointmentRate',message:'Discuss payment options'},strength:{enabled:false}}},{id:'b',title:'QA',baseName:'QA 90',ruleType:'multiHeader'},{id:'c',title:'Stats',baseName:'Insurance',ruleType:'statRule'}];
assert.deepEqual(workflow.matchingRules('Insurance Cash.xlsx',rules).map(r=>r.id),['a']);
assert.equal(workflow.matchingRules('Unknown.xlsx',rules).length,0);
assert.equal(workflow.matchingRules('Insurance Cash.xlsx',[...rules,{id:'d',baseName:'Insurance',ruleType:'multiHeader'}]).length,2,'ambiguous filenames must be exposed, not silently resolved');
for(const query of ['insurance','cashAppointmentRate','payment options']) assert.ok(workflow.matchesSearch(rules[0],query));
assert.ok(!workflow.matchesSearch(rules[0],'unrelated'));
rules[0].title='New title'; workflow.invalidateSearch(rules[0]); assert.ok(workflow.matchesSearch(rules[0],'new title'),'editing invalidates search text');
const attachment={fingerprint:workflow.fingerprint(rules)};
assert.equal(workflow.rulesetStatus(null,rules).kind,'none');
assert.equal(workflow.rulesetStatus(attachment,rules).kind,'current');
assert.equal(workflow.rulesetStatus(attachment,rules,true).kind,'dirty');
rules[0].updatedAt='today';assert.equal(workflow.rulesetStatus(attachment,rules).kind,'current','auto-save timestamp alone does not dirty file content');
rules[0].individualMessage.concern.message='Changed';assert.equal(workflow.rulesetStatus(attachment,rules).kind,'dirty');
attachment.fingerprint=workflow.fingerprint(rules);assert.equal(workflow.rulesetStatus(attachment,rules).kind,'current');
assert.equal(workflow.rulesetStatus({...attachment,error:'Invalid file'},rules).kind,'review');
assert.equal(engine.normalizeTemplate().maxConcerns,1);assert.equal(engine.DEFAULT_TEMPLATE.maxConcerns,1);assert.equal(engine.DEFAULT_TEMPLATE.maxStrengths,2);
assert.equal(engine.normalizeTemplate({maxConcerns:0,maxStrengths:0}).maxConcerns,0,'saved unlimited stays unlimited');
assert.equal(engine.normalizeTemplate({header:'Saved before limits existed'}).maxConcerns,0,'legacy settings retain unlimited behavior');
assert.equal(engine.normalizeTemplate({maxConcerns:4,maxStrengths:5}).maxStrengths,5);
const representative={repKey:'rep',fullName:'Alex Able'};
const roster=[{'First Name':'Alex','Last Name':'Able',Username:'alex@example.com'}];
const evaluationRules=Array.from({length:4},(_,i)=>({id:String(i),title:'Rule '+i,individualMessage:{concern:{enabled:true,sourceType:'stat',source:'score',operator:'lt',threshold:'50',message:'Concern '+i},strength:{enabled:true,sourceType:'stat',source:'score',operator:'gte',threshold:'1',message:'Strength '+i}}}));
const resolver={resolveVariable(){return {missing:true};},resolveObservation(){return {value:20,raw:20,formatted:'20',missing:false};}};
const result=engine.evaluateAll({representatives:[representative],rules:evaluationRules,rosterRows:roster,resolver,template:{...engine.DEFAULT_TEMPLATE,includeGeneric:true,genericMessage:'Weekly note'}}).results[0];
assert.equal(result.concerns.length,1);assert.equal(result.strengths.length,2);assert.equal(result.qualifyingConcernCount,4,'limits do not alter qualifying counts');
for(const placement of ['before','after']){
  const evaluated=engine.evaluateAll({representatives:[representative],rules:evaluationRules,rosterRows:roster,resolver,template:{...engine.DEFAULT_TEMPLATE,includeGeneric:true,genericMessage:'Weekly note',genericPlacement:placement}}).results[0];
  const fields=workflow.emailFields(evaluated,{genericPlacement:placement});
  assert.deepEqual(Object.keys(fields),workflow.EMAIL_COLUMNS);
  assert.equal(workflow.EMAIL_COLUMNS.slice(2).map(key=>fields[key]).filter(Boolean).join('\n\n'),evaluated.message,'preview/export preserves the fully rendered message and generic placement');
}
let written,notices=[];
const context=vm.createContext({state:{rules,dashboardFiles:[{id:'f',ruleId:'a',status:'matched'}],individualResults:[result,{...result,sendReady:false,email:''}],individualTemplate:{genericPlacement:'before'}},QualtricsWorkflow:workflow,QualtricsIndividualMessages:engine,XLSX:{...XLSX,writeFile(wb){written=wb;}},window:{XLSX},toast:message=>notices.push(message),ymd:()=> '2026-09-08',console});
vm.runInContext(ui,context);
vm.runInContext(html.slice(html.indexOf('function autoSelectUploadedRules('),html.indexOf('function currentRule()')),context);
vm.runInContext(html.slice(html.indexOf('function autoSelectCoreRules('),html.indexOf('function autoSelectUploadedRules(')),context);
Object.assign(context,{isStatRule:rule=>rule.ruleType==='statRule',isStatCountRule:rule=>rule.ruleType==='statCount',isCoachingCorrectiveRule:rule=>rule.ruleType==='coachingCorrective',isCoreDataRule:rule=>['statRule','statCount','coachingCorrective'].includes(rule.ruleType),headerKey:value=>String(value||'').toLowerCase().replace(/[^a-z0-9]/g,''),saveOtherRuleSelection(){}});
context.state.masterRows={qa:[{raw:{Score:90}}]};context.state.selectedOtherRuleIds=new Set();
const coreRule={id:'qa-count',ruleType:'statCount',statCount:{source:'qa'}};context.state.rules.push(coreRule);
context.autoSelectCoreRules('qa');assert.ok(context.individualRuleSelection().has('qa-count'));assert.ok(context.state.selectedOtherRuleIds.has('qa-count'));assert.ok(!context.individualRuleSelection().has('c'),'QA upload does not select a Weekly Stats rule');
context.individualRuleSelection().clear();context.state.rules.pop();
context.autoSelectUploadedRules([{id:'f',ruleId:'a',status:'matched'},{id:'err',status:'error'}]);
assert.ok(context.individualRuleSelection().has('a'));assert.ok(!context.individualRuleSelection().has('b'));assert.ok(context.individualReportSelection().has('f'));assert.ok(!context.individualReportSelection().has('err'));
context.ruleNeedsReportFile=rule=>!context.isCoreDataRule(rule);
context.state.individualRosterRows=roster;context.state.dashboardFiles[0].headers=['Score'];
context.state.rules[0].individualMessage.concern={enabled:true,sourceType:'reportField',field:'Score',operator:'lt',threshold:'50',message:'Review score'};
assert.equal(context.individualPreflight()[0].issues.length,0,'known field and roster pass source preflight');
context.state.dashboardFiles[0].headers=[];
assert.ok(context.individualPreflight()[0].issues.some(issue=>issue.includes('Report column missing')),'missing fields are shown before evaluation');
context.individualRuleSelection().delete('a'); assert.equal(context.individualSelectedRules().length,0,'manual deselection remains authoritative');
context.exportFinalIndividualEmails();
const bytes=XLSX.write(written,{type:'buffer',bookType:'xlsx'}), roundTrip=XLSX.read(bytes,{type:'buffer'});
assert.deepEqual(roundTrip.SheetNames,['Email Messages']);
const rows=XLSX.utils.sheet_to_json(roundTrip.Sheets['Email Messages'],{header:1});
assert.deepEqual(rows[0],workflow.EMAIL_COLUMNS);assert.equal(rows.length,2,'only send-ready people are exported');assert.equal(rows[1][0],'Alex Able');
written=null;context.state.individualResultsStale=true;context.exportFinalIndividualEmails();assert.equal(written,null,'stale review cannot export');
const nav=html.slice(html.indexOf('<nav class="tabs">'),html.indexOf('</nav>'));
for(const tab of ['orgsummary','coachprofiles','overallcoaching','topicimpact']) assert.ok(!nav.includes(`data-tab="${tab}"`));
assert.ok(html.includes('id="individualPreflight"'));
// Superseded All-Star bridge conversion must stop by the next yield boundary.
const bridge=fs.readFileSync(path.join(__dirname,'../js/qualtrics-bridge.js'),'utf8');
const bridgeContext=vm.createContext({setTimeout,console});vm.runInContext(bridge,bridgeContext);
(async()=>{
  let count=0;bridgeContext.qualtricsBridgeRow=row=>{count++;return row;};
  await assert.rejects(()=>bridgeContext.qualtricsBridgeRowsDeferred(Array.from({length:5000},()=>({x:1})),'qa','',()=>count<1500),{name:'AbortError'});
  assert.equal(count,1500,'cancelled conversion skips remaining rows');
  const original=[{x:1},{x:2}], converted=await bridgeContext.qualtricsBridgeRowsDeferred(original,'qa');assert.equal(JSON.stringify(converted),JSON.stringify(original));
  console.log('PASS Qualtrics workflow: selection, defaults, export round-trip, status, search, navigation, bridge cancellation');
})().catch(error=>{console.error(error);process.exitCode=1;});
