'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const {parseHTML}=require('linkedom');
const root=path.resolve(__dirname,'..');
const context=vm.createContext({console,setTimeout,clearTimeout});context.window=context;
vm.runInContext(fs.readFileSync(path.join(root,'shared/coachtools-import.js'),'utf8'),context);
const api=context.CoachToolsImport;
const parsed=rows=>({meta:{totalRows:rows.length},workbook:{sheets:['Data'],data:{Data:{aoa:rows}}}});
const entry={file:{name:'<unidentified> 08-01 to 08-07 2026.xlsx'},parsed:parsed([['Sheet','Representative'],['Coach A','Jane Doe']]),classification:{id:null,candidates:['weeklyRetail','weeklyReferral']}};
const fixtures={weeklyRetail:['Sheet'],weeklyReferral:['Representative'],monthlyRetail:['Phone_ID'],monthlyReferral:['KPI Summary'],qa:['Team','Score %'],documentedCoaching:['Job Coach','Coaching Date'],checklist:['Coach Assigned','Action'],compCoaching:['CSR/SSR Name','Comments']};
for(const [type,headers] of Object.entries(fixtures))assert(api.validateClassification(type,parsed([headers,['A',90]])).valid,type);
const badQA=api.validateClassification('qa',entry.parsed);
assert.equal(badQA.missing.length,2);assert.match(badQA.reason,/Missing team or agent column/);assert.match(badQA.reason,/Score %/);
const goodQA=api.validateClassification('qa',parsed([['Team'],['Coach A']]));assert.equal(goodQA.missing.length,1);assert.match(goodQA.reason,/evaluation field/);
const tick=()=>new Promise(resolve=>setTimeout(resolve,0));
function choose(select,value){ // linkedom provides a getter-only HTMLSelectElement.value.
 for(const option of select.options)option.removeAttribute("selected");
 Array.from(select.options).find(option=>option.value===value).selected=true;
 select.dispatchEvent(new context.document.defaultView.Event('change'));
}
(async()=>{
 let writes=0;context.CoachToolsData={importDataset:async()=>{writes++;return {status:'imported'}}};
 const original=JSON.stringify(entry);
 await assert.rejects(()=>api.assignSource(entry,'qa'),/Missing team or agent/);assert.equal(JSON.stringify(entry),original);assert.equal(writes,0);
 const assigned=await api.assignSource(entry,'weeklyReferral');assert.equal(assigned.classification.id,'weeklyReferral');assert(assigned.classification.manualSourceSelection);assert.equal(assigned.file,entry.file);assert.equal(writes,0);
 await assert.rejects(()=>api.assignSource(entry,'invalid'),/supported data source/);
 const XLSX=require('../vendor/xlsx.full.min.js');context.XLSX=XLSX;
 const workbook=XLSX.utils.book_new();XLSX.utils.book_append_sheet(workbook,XLSX.utils.aoa_to_sheet([['Sheet','Representative'],['Coach A','Jane Doe']]),'Data');
 const bytes=XLSX.write(workbook,{type:'array',bookType:'xlsx'});
 const uploaded={name:'Unknown 08-01 to 08-07 2026.xlsx',size:bytes.byteLength,arrayBuffer:async()=>bytes};
 const discovered=await api.discoverFile(uploaded);assert.equal(discovered.classification.id,null);
 const resolvedWorkbook=await api.assignSource(discovered,'weeklyRetail');
 assert.equal(resolvedWorkbook.classification.id,'weeklyRetail');
 assert.equal(resolvedWorkbook.discovery.ownershipValues[0].value,'Coach A','manual source selection must rebuild coach discovery');
 assert.equal(discovered.classification.id,null,'the unresolved original stays unchanged until a choice succeeds');
 const prepared=await api.prepareRecognizedEntry(resolvedWorkbook,{scope:{mode:'coach',coaches:['Coach A']}});
 assert.equal(prepared.matchedRows,1,'manual choice must preserve the normal scope filter');
 const {document}=parseHTML('<html><body><button id="before">Upload</button></body></html>');context.document=document;
 const analysis={recognized:[],needsReview:[entry],errors:[]};
 const done=api.resolveUnidentifiedFiles(analysis,{manualSourceSelection:true});
 const dialog=document.querySelector('dialog'),select=dialog.querySelector('select'),buttons=dialog.querySelectorAll('button');
 assert(dialog);assert.equal(select.options.length,9);assert.equal(dialog.querySelector('strong').textContent,entry.file.name);assert.equal(dialog.querySelector('unidentified'),null,'filename must render as text');
 choose(select,'qa');buttons[0].click();await tick();assert.match(dialog.textContent,/snip the report/);assert.match(dialog.textContent,/Missing team or agent/);assert.equal(analysis.recognized.length,0);assert.equal(writes,0);
 choose(select,'weeklyRetail');buttons[0].click();await tick();assert.equal(analysis.recognized.length,1);assert.equal(analysis.needsReview.length,0);assert.equal(writes,0,'picker only validates, never bypasses scoped save');
 buttons[0].click();assert.equal(analysis.recognized.length,0);assert.equal(analysis.needsReview.length,1,'confirmed source can be corrected before upload');
 choose(select,'weeklyReferral');buttons[0].click();await tick();buttons[1].click();await done;assert.equal(document.querySelector('dialog'),null);assert.equal(analysis.recognized[0].classification.id,'weeklyReferral');
 await api.saveRecognizedEntry(analysis.recognized[0],{scope:{mode:'all'}});assert.equal(writes,1);
 const skipped={recognized:[],needsReview:[entry],errors:[]};const skipDone=api.resolveUnidentifiedFiles(skipped,{manualSourceSelection:true});document.querySelector('dialog').dispatchEvent(new document.defaultView.Event('cancel',{cancelable:true}));await skipDone;assert.equal(skipped.needsReview.length,1);assert.equal(writes,1,'skipping must retain old data');
 console.log('Manual source recovery: detailed format diagnostics, correction/retry/skip, text-safe UI, and validated scoped save passed.');
})().catch(error=>{console.error(error);process.exitCode=1;});
